apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - namespace.yaml
  - certificate.yaml
  - cockroach.yaml
  - redis.yaml
  - timescale.yaml
configMapGenerator:
  - name: redis-tools
    files:
      - motd=redis-motd
      - bashrc=redis-bashrc
  - name: cockroach-tools
    files:
      - motd=cockroach-motd
      - bashrc=cockroach-bashrc
  - name: timescale-tools
    files:
      - motd=timescale-motd
      - bashrc=timescale-bashrc
generatorOptions:
  disableNameSuffixHash: true
