apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - namespace.yaml
  - certificate.yaml
  - cockroach-configmap.yaml
  - cockroach.yaml
  - redis-configmap.yaml
  - redis.yaml
  - timescale-configmap.yaml
  - timescale.yaml
images:
  - name: cockroachdb/cockroach
    newTag: v24.2.4
  - name: bitnami/redis-cluster
    newTag: 6.2.16-debian-12-r3@sha256:d973a2aa8b6688190ca4e4544b2ff859ef1e9f8081518558270df34e23ff1df7
  - name: timescale/timescaledb-ha
    newTag: pg14.15-ts2.17.2
