apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - namespace.yaml
  - certificate.yaml
  - cockroach-configmap.yaml
  - cockroach.yaml
  - redis-configmap.yaml
  - redis.yaml
  - timescale-configmap.yaml
  - timescale.yaml
