apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client-secure
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: redis-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-client
    spec:
      containers:
        - name: redis-client
          image: bitnami/redis-cluster
          volumeMounts:
            - name: client-certs
              mountPath: /client-certs
            - name: motd
              mountPath: /etc/motd
              subPath: motd
            - name: bashrc
              mountPath: /etc/bash.bashrc
              subPath: bash.bashrc
          command:
            - sleep
            - "2147483648"
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 512Mi
      volumes:
        - name: client-certs
          projected:
            defaultMode: 0400
            sources:
              - secret:
                  name: tools-tls
                  items:
                    - key: ca.crt
                      path: ca.crt
                      mode: 0400
                    - key: tls.crt
                      path: client.acp.crt
                      mode: 0400
                    - key: tls.key
                      path: client.acp.key
                      mode: 0400
        - name: motd
          projected:
            sources:
              - configMap:
                  name: redis-tools
                  items:
                    - key: motd
                      path: motd
                      mode: 0644
        - name: bashrc
          projected:
            sources:
              - configMap:
                  name: redis-tools
                  items:
                    - key: bashrc
                      path: bash.bashrc
                      mode: 0644
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
