apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
resources:
  - namespace.yaml
  - repository.yaml
  - tls.yaml
  - release.yaml
  - cronjob.yaml
configMapGenerator:
  - name: redis-node-sync
    files:
      - node-sync.sh
secretGenerator:
  - name: redis-values
    files:
      - values.yaml=redis-values.enc.yaml
generatorOptions:
  disableNameSuffixHash: true
