# Production Readiness - Use Your Own Secret
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-exporter
spec:
  releaseName: elastic-exporter
  chart:
    spec:
      chart: prometheus-elasticsearch-exporter
      sourceRef:
        kind: HelmRepository
        name: elastic-exporter
      version: 6.7.3
  interval: 60m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/values.yaml
  valuesFrom:
    - kind: Secret
      name: elastic-exporter-values
  values:
    serviceMonitor:
      enabled: true
    es:
      sslSkipVerify: true
      all: false
      indices_settings: false
      indices_mappings: false
      shards: false
