apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: apm-agent
spec:
  version: 8.13.2 # {"$imagepolicy": "elastic:elastic-agent-image-policy-prod:tag"}
  kibanaRef:
    name: kibana
  fleetServerRef:
    name: apm-fleet-server
  mode: fleet
  secureSettings:
    - secretName: apm-token
  deployment:
    replicas: 2
    podTemplate:
      spec:
        affinity:
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/statefulset-name: elastic-es-hot-nodes
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: agent
            securityContext:
              runAsUser: 0
              capabilities:
                drop:
                  - ALL
                add: ["NET_BIND_SERVICE"]
              allowPrivilegeEscalation: false
              seccompProfile:
                type: "RuntimeDefault"
            volumeMounts:
              - name: tls
                mountPath: "/tls"
                readOnly: true
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 2Gi
        nodeSelector:
          elastic: "true"
        tolerations:
          - key: elastic
            value: "true"
            effect: NoSchedule
        volumes:
          - name: tls
            secret:
              secretName: apm-tls
          - name: agent-data
            emptyDir: {}
        securityContext:
          capabilities:
            drop:
              - ALL
            add: ["NET_BIND_SERVICE"]
          seccompProfile:
            type: "RuntimeDefault"
