apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: apm-fleet-server
spec:
  version: 8.14.3 # {"$imagepolicy": "elastic:elastic-agent-image-policy-prod:tag"}
  kibanaRef:
    name: kibana
  elasticsearchRefs:
    - name: elastic
  mode: fleet
  fleetServerEnabled: true
  secureSettings:
    - secretName: apm-token
  policyID: eck-fleet-server
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        containers:
          - name: agent
            securityContext:
              runAsUser: 0
              capabilities:
                drop:
                  - ALL
                add: ["NET_BIND_SERVICE"]
              allowPrivilegeEscalation: false
              seccompProfile:
                type: "RuntimeDefault"
            resources:
              requests:
                memory: 200Mi
              limits:
                memory: 600Mi
        volumes:
          - name: agent-data
            emptyDir: {}
        securityContext:
          capabilities:
            drop:
              - ALL
            add: ["NET_BIND_SERVICE"]
          fsGroup: 1000
          seccompProfile:
            type: "RuntimeDefault"
  http:
    tls:
      certificate:
        secretName: apm-tls
