apiVersion: v1
kind: ConfigMap
metadata:
  name: snapshot-repositories
data:
  default-repository.json: |-
    {
        "name": "default",
        "type": "s3",
        "settings": {
            "bucket": "elasticsearch",
            "endpoint": "minio.minio:9000",
            "path_style_access": "true"
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snapshot-policies
data:
  default-policy.json: |-
    {
        "name": "default-daily-snap",
        "snapshotName": "<daily-snap-{now/d}>",
        "schedule": "0 0 3 * * ?",
        "repository": "default",
        "config": {
            "featureStates": [],
            "includeGlobalState": true,
            "partial": true
        },
        "retention": {
            "expireAfterValue": 3,
            "expireAfterUnit": "d",
            "maxCount": 100,
            "minCount": 10
        },
        "isManagedPolicy": false
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-pipelines
data:
  id_token_ingest_pipeline.json: |-
    {
      "name": "id-token-ingest-pipeline",
      "description": "Pipeline to mask id_token_hint",
      "processors": [
        {
          "gsub": {
            "field": "message",
            "pattern": "(id_token_hint=)[^&]*",
            "replacement": "$1*****",
            "ignore_missing": true
          }
        }
      ]
    }
