apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-snapshot-setup
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 8
  template:
    spec:
      volumes:
        - name: snapshot-policies
          configMap:
            name: snapshot-policies
        - name: snapshot-repositories
          configMap:
            name: snapshot-repositories
      containers:
        - name: kibana-snapshot-setup
          image: curlimages/curl:8.14.1@sha256:9a1ed35addb45476afa911696297f8e115993df459278ed036182dd2cd22b67b
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: snapshot-policies
              mountPath: /data/policies
            - name: snapshot-repositories
              mountPath: /data/repositories
          command: ["/bin/sh", "-c"]
          env:
            - name: KB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-setup-credentials
                  key: username
            - name: KB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-setup-credentials
                  key: password
            - name: KIBANA_URL
              value: "https://kibana-kb-http.elastic.svc:5601"
          args:
            - |
              #!/bin/sh
              curl \
                --retry-all-errors --retry 5 --retry-delay 30 \
                --insecure --fail \
                --silent --write-out '%{http_code}' --output /dev/null \
                $KIBANA_URL/login
              echo "Kibana is ready"

              sleep 10

              curl \
                -u "$KB_USERNAME:$KB_PASSWORD" \
                --fail --insecure --silent \
                --write-out "%{errormsg}" \
                -H "kbn-xsrf: true" \
                $KIBANA_URL/api/snapshot_restore/repositories/default ||\
              curl -X PUT \
                -u "$KB_USERNAME:$KB_PASSWORD" \
                --insecure --fail \
                --silent --write-out "%{errormsg}" --include \
                -H 'Content-Type: application/json' \
                -H "kbn-xsrf: true" \
                $KIBANA_URL/api/snapshot_restore/repositories \
                --data-binary "@/data/repositories/default-repository.json"

              curl \
                -u "$KB_USERNAME:$KB_PASSWORD" \
                --fail --insecure --silent \
                --write-out "%{errormsg}" \
                -H "kbn-xsrf: true" \
                $KIBANA_URL/api/snapshot_restore/policy/default-daily-snap ||\
              curl -X POST \
                -u "$KB_USERNAME:$KB_PASSWORD" \
                --insecure --write-out "%{errormsg}" --fail \
                --silent --include \
                -H 'Content-Type: application/json' \
                -H "kbn-xsrf: true" \
                $KIBANA_URL/api/snapshot_restore/policies \
                --data-binary "@/data/policies/default-policy.json"
          securityContext:
            capabilities:
              drop:
                - ALL
              add: ["NET_BIND_SERVICE"]
            allowPrivilegeEscalation: false
      imagePullSecrets:
        - name: artifactory
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
