apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elastic
resources:
  - elastic_exporter.yaml
  - elastic.yaml
  - filebeat.yaml
  - fleet_apm_agents.yaml
  - fleet_server.yaml
  - ingress.yaml
  - init_job_ingest.yaml
  - init_job_snapshot.yaml
  - init_job_ilm.yaml
  - kibana.yaml
  - metricbeat.yaml
  - namespace.yaml
  - operator.yaml
  - rbac.yaml
  - repository.yaml
  - role.yaml
  - service.yaml
  - serviceaccount.yaml
  - tls.yaml
configMapGenerator:
  - name: snapshot-repositories
    files:
      - default-repository.json=snapshot-repository.json
  - name: snapshot-policies
    files:
      - default-policy.json=snapshot-policy.json
  - name: ingest-pipelines
    files:
      - id_token_ingest_pipeline.json=ingest_pipeline.json
  - name: metricbeat-ilm
    files:
      - policy.json=metricbeat-ilm.json
  - name: filebeat-ilm
    files:
      - policy.json=filebeat-ilm.json
  - name: ilm
    files:
      - apm.json=apm-ilm.json
  - name: components
    files:
      - traces-apm.json=components-apm.json
secretGenerator:
  - name: filerealm
    files:
      - users=filerealm-users.enc.txt
      - users_roles=filerealm-roles.enc.txt
  - name: kibana-secret-settings
    envs:
      - kibana-secret-settings.enc.env
  - name: apm-token
    envs:
      - apm-token.enc.env
  - name: elastic-setup-credentials
    envs:
      - elastic-setup-credentials.enc.env
  - name: elastic-exporter-values
    files:
      - values.yaml=elastic-exporter-values.enc.yaml
  - name: minio-credentials
    envs:
      - minio-credentials.enc.env
generatorOptions:
  disableNameSuffixHash: true
