apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elastic
resources:
  - elastic.yaml
  - fleet_apm_agents.yaml
  - fleet_server.yaml
  - ingress.yaml
  - kibana.yaml
  - namespace.yaml
  - operator.yaml
  - rbac.yaml
  - repository.yaml
  - role.yaml
  - service.yaml
  - serviceaccount.yaml
  - tls.yaml
  - metricbeat.yaml
  - filebeat.yaml
  - elastic_exporter.yaml
  - filerealm.yaml
  - secret.yaml
  - init_configs.yaml
  - init_job.yaml
