apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: eck-operator
spec:
  releaseName: elastic-operator
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic
      version: 2.11.1 # helm:autoupdate:eck-operator-prod
  interval: 5m
  timeout: 15m
  # https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-operator/values.yaml
  values:
    image:
      tag: 2.11.0 # {"$imagepolicy": "elastic:eck-operator-image-policy-prod:tag"}
    installCRDs: false
    nodeSelector:
      elastic: "true"
    tolerations:
      - key: elastic
        value: "true"
        effect: NoSchedule
    createClusterScopedResources: true
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
