apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic
spec:
  interval: 6h
  url: https://helm.elastic.co
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic-exporter
spec:
  interval: 6h
  url: https://prometheus-community.github.io/helm-charts
