apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: disallow-capabilities-kube-system
spec:
  background: true
  exceptions:
    - policyName: disallow-capabilities
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - kube-system
          names:
            - aws-node*
            - ebs-csi-node*
            - kindnet*
            - node-local-dns*
            - etcd*
            - kube-apiserver*
            - kube-controller*
            - kube-scheduler*
            - eks-pod-identity-agent*
            - eks-node-monitoring-agent*
---
# redisinsight requires CAP_IPC_LOCK capability as it uses gnome-keyring-daemon
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: disallow-capabilities-redisinsight
spec:
  background: true
  exceptions:
    - policyName: disallow-capabilities
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Deployment
            - Pod
            - ReplicaSet
          namespaces:
            - redisinsight
          names:
            - redisinsight*
