apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-capabilities-kube-system
spec:
  background: true
  exceptions:
    - policyName: disallow-capabilities
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - kube-system
          names:
            - aws-node*
            - ebs-csi-node*
            - kindnet*
            - node-local-dns*
            - etcd*
            - kube-apiserver*
            - kube-controller*
            - kube-scheduler*
---
# required to perform chaos experiments
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-capabilities-chaos-mesh
spec:
  background: true
  exceptions:
    - policyName: disallow-capabilities
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Deployment
            - Pod
            - ReplicaSet
          namespaces:
            - chaos-mesh
          names:
            - chaos-daemon*
---
# redisinsight2 requires CAP_IPC_LOCK to work correctly
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-capabilities-redisinsight
spec:
  background: true
  exceptions:
    - policyName: disallow-capabilities
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Deployment
            - Pod
            - ReplicaSet
          namespaces:
            - redisinsight
          names:
            - redisinsight2*
