apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-host-path-lacework
spec:
  background: true
  exceptions:
    - policyName: disallow-host-path
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Deployment
            - Pod
            - StatefulSet
          namespaces:
            - lacework
          names:
            - lacework-agent*
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-host-path-elastic
spec:
  background: true
  exceptions:
    - policyName: disallow-host-path
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Deployment
            - Pod
            - StatefulSet
          namespaces:
            - elastic
          names:
            - filebeat-beat-*
---
# Required in order to gather metrics about node by node exporter
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-host-path-prometheus-node-exporter
spec:
  background: true
  exceptions:
    - policyName: disallow-host-path
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - monitoring
          names:
            - kube-prometheus-stack-prometheus-node-exporter*
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-host-path-kube-system
spec:
  background: true
  exceptions:
    - policyName: disallow-host-path
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - kube-system
          names:
            - aws-node*
            - ebs-csi-node*
            - kindnet*
            - kube-proxy*
            - node-local-dns*
            - node-problem-detector*
            - etcd*
            - kube-apiserver*
            - kube-controller*
            - kube-scheduler*
---
# required to perform chaos experiments
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-host-path-chaos-mesh
spec:
  background: true
  exceptions:
    - policyName: disallow-host-path
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Deployment
            - Pod
            - ReplicaSet
          namespaces:
            - chaos-mesh
          names:
            - chaos-daemon*
