apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: disallow-privilege-escalation-elastic
spec:
  background: true
  exceptions:
    - policyName: disallow-privilege-escalation
      ruleNames:
        - autogen-privilege-escalation
        - privilege-escalation
  match:
    any:
      - resources:
          kinds:
            - Pod
            - StatefulSet
          namespaces:
            - elastic
          names:
            - elastic-es-*
---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: disallow-privilege-escalation-lacework
spec:
  background: true
  exceptions:
    - policyName: disallow-privilege-escalation
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Deployment
            - Pod
            - ReplicaSet
            - StatefulSet
          namespaces:
            - lacework
          names:
            - lacework-agent*
---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: disallow-privilege-escalation-kube-system
spec:
  background: true
  exceptions:
    - policyName: disallow-privilege-escalation
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - kube-system
          names:
            - aws-node*
            - ebs-csi-node*
            - kindnet*
            - kube-proxy*
            - node-local-dns*
            - node-problem-detector*
            - etcd*
            - kube-apiserver*
            - kube-controller*
            - kube-scheduler*
---
# required to perform chaos experiments
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: disallow-privilege-escalation-chaos-mesh
spec:
  background: true
  exceptions:
    - policyName: disallow-privilege-escalation
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Deployment
            - Pod
            - ReplicaSet
          namespaces:
            - chaos-mesh
          names:
            - chaos-daemon*
---
# required to perform chaos experiments
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: disallow-privilege-escalation-cockroach-init-job
spec:
  background: true
  exceptions:
    - policyName: disallow-privilege-escalation
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Job
            - Pod
          namespaces:
            - cockroachdb*
          names:
            - cockroachdb-local-vcheck*
