apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: require-run-as-non-root-user-elastic
spec:
  background: true
  exceptions:
    - policyName: require-run-as-non-root-user
      ruleNames:
        - autogen-run-as-non-root-user
        - run-as-non-root-user
  match:
    any:
      - resources:
          kinds:
            - Pod
            - ReplicaSet
            - Deployment
            - StatefulSet
            - DaemonSet
          namespaces:
            - elastic
          names:
            - apm-agent-agent*
            - apm-fleet-server*
            - metricbeat*
            - filebeat*
            - elastic-es-*
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: require-run-as-non-root-user-lacework
spec:
  background: true
  exceptions:
    - policyName: require-run-as-non-root-user
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Deployment
            - Pod
            - StatefulSet
          namespaces:
            - lacework
          names:
            - lacework-agent*
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: require-run-as-non-root-user-tools
spec:
  background: true
  exceptions:
    - policyName: require-run-as-non-root-user
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Deployment
            - Pod
            - ReplicaSet
          namespaces:
            - tools
          names:
            - cockroachdb*
---
# db-init job requires to run as root to change permissions
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: require-run-as-non-root-user-cockroachdb
spec:
  background: true
  exceptions:
    - policyName: require-run-as-non-root-user
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Deployment
            - Job
            - Pod
            - StatefulSet
          namespaces:
            - cockroachdb*
          names:
            - cockroachdb*
---
# unable to start pipeline otherwise
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: require-run-as-non-root-user-observability
spec:
  background: true
  exceptions:
    - policyName: require-run-as-non-root-user
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - observability*
          names:
            - opentelemetry-collector*
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: require-run-as-non-root-user-kube-system
spec:
  background: true
  exceptions:
    - policyName: require-run-as-non-root-user
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Deployment
            - Pod
            - ReplicaSet
          namespaces:
            - kube-system
          names:
            - aws-node*
            - ebs-csi-node*
