apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: restrict-seccomp-strict-lacework
spec:
  background: true
  exceptions:
    - policyName: restrict-seccomp-strict
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Deployment
            - Pod
            - ReplicaSet
            - StatefulSet
          namespaces:
            - lacework
          names:
            - lacework-agent*
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: restrict-seccomp-strict-kube-system
spec:
  background: true
  exceptions:
    - policyName: restrict-seccomp-strict
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
            - StatefulSet
            - ReplicaSet
            - Deployment
          namespaces:
            - kube-system
          names:
            - kindnet*
            - kube-proxy*
            - coredns*
