apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux
spec:
  groups:
    - name: flux
      rules:
        - alert: ReconciliationFailure
          expr: gotk_resource_info{ready="False"} == 1
          for: 1h
          labels:
            severity: warning
          annotations:
            description: "{{ $labels.customresource_kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} reconciliation has been failing for more than ten minutes"
            summary: Reconciliation has failed
        - alert: ReconciliationFailure
          expr: gotk_resource_info{ready="False",customresource_kind=~"HelmRelease|Kustomization"} == 1
          for: 4h
          labels:
            severity: critical
          annotations:
            description: "{{ $labels.customresource_kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} reconciliation has been failing for more than one hour"
            summary: Reconciliation has failed
        - alert: ReconciliationSuspended
          expr: gotk_suspend_status == 1
          for: 30m
          labels:
            severity: warning
          annotations:
            description: "{{ $labels.kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} reconciliation has been suspended for more than thirty minutes"
            summary: Reconciliation Suspended
