apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kyverno
spec:
  groups:
    - name: kyverno-policies
      rules:
        - alert: KyvernoPolicyViolation
          expr: sum by (policy, exported_namespace, name) (policy_report_result{status="fail"}) > 0
          labels:
            severity: warning
          annotations:
            description: "Resources did not fulfil policy {{ $labels.policy }} on {{ $labels.exported_namespace }}"
            summary: Resources did not fullfill kyverno policies.
