hazelcast:
  enabled: true
cockroachdb:
  enabled: true
acp:
  enabled: true
  serverURL: "https://authorization.cloudentity.com:8443"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-ssl-ciphers: "EECDH+AESGCM:EDH+AESGCM"
      nginx.ingress.kubernetes.io/proxy-ssl-protocols: "TLSv1.2"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
      nginx.ingress.kubernetes.io/ssl-ciphers: "EECDH+AESGCM:EDH+AESGCM"
      nginx.ingress.kubernetes.io/server-snippet: |
        ssl_verify_client optional_no_ca;
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-SSL-CERT $ssl_client_escaped_cert;
    hosts:
      - host: authorization.cloudentity.com
        paths:
          - path: /