apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  values:
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        interval: ""
