apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acp
resources:
  - ../base
  - scaled_object.yaml
  - servicemonitor.yaml
  - metrictemplate.yaml
  - canary.yaml
  - canary_workers.yaml
patches:
  - path: release.yaml
