apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: acp
spec:
  values:
    args:
      - server
      - start
      - --demo
      - --metrics
      - --create-default-tenant
      - --create-default-workspaces
    config:
      data:
        otel:
          propagators:
            - jaeger
            - tracecontext
          jaeger:
            header: "x-trace-id"
        docker:
          shared_node_url: "http://acp-faas-nodejs-v4-proxy.acp-faas:8080"
          shared_rego_url: "http://acp-faas-rego-v5-proxy.acp-faas:8080"
    certManager:
      extraNames:
        - acp-primary
        - acp-primary.acp
        - acp-primary.acp.svc.cluster.local
        - acp-canary
        - acp-canary.acp
        - acp-canary.acp.svc.cluster.local
    service:
      enabled: false
    env:
      - name: DEFAULT_IMPORT_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: client-secret
            key: default-import-client-secret
      - name: OTEL_JAEGER_AGENT_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: PodDisruptionBudget
              name: acp
              version: v1
            patch:
              - op: add
                path: /spec/selector/matchLabels
                value:
                  app.kubernetes.io/name: acp-primary
          - target:
              kind: PodDisruptionBudget
              name: acp-workers
              version: v1
            patch:
              - op: add
                path: /spec/selector/matchLabels
                value:
                  app.kubernetes.io/name: acp-workers-primary
