apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: acp-canary
spec:
  endpoints:
    - port: metrics
      interval: 10s
      metricRelabelings:
        - sourceLabels: [env]
          targetLabel: faas_env
          action: replace
  selector:
    matchLabels:
      app.kubernetes.io/name: acp-canary
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: acp-primary
spec:
  endpoints:
    - port: metrics
      metricRelabelings:
        - sourceLabels: [env]
          targetLabel: faas_env
          action: replace
  selector:
    matchLabels:
      app.kubernetes.io/name: acp-primary
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: acp-workers-canary
spec:
  endpoints:
    - port: metrics
      interval: 10s
      metricRelabelings:
        - sourceLabels: [env]
          targetLabel: faas_env
          action: replace
  selector:
    matchLabels:
      app.kubernetes.io/name: acp-workers-canary
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: acp-workers-primary
spec:
  endpoints:
    - port: metrics
      metricRelabelings:
        - sourceLabels: [env]
          targetLabel: faas_env
          action: replace
  selector:
    matchLabels:
      app.kubernetes.io/name: acp-workers-primary
