apiVersion: v1
kind: Service
metadata:
  name: acp
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: http
    - name: metrics
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: grpc
      port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: acp
