apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: acp
spec:
  interval: 2m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  path: ./apps/acp/base
  postBuild:
    substituteFrom:
      - kind: Secret
        name: docker-cloudentity
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: acp
      namespace: acp
  dependsOn:
    - name: nginx
    - name: cockroachdb
    - name: redis
    - name: timescaledb
    - name: spicedb
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: acp-faas
spec:
  interval: 5m
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  path: ./apps/acp-faas/base
  postBuild:
    substituteFrom:
      - kind: Secret
        name: docker-cloudentity
  dependsOn:
    - name: nginx
