apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
spec:
  interval: 24h
  timeout: 15m
  retryInterval: 2m
  prune: false
  path: ./crds/base
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster
