apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - apps.yaml
  - crds.yaml
  - infrastructure.yaml
  - middleware.yaml
  - lightweight-tests.yaml
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
    patch: |-
      kind: Kustomization
      metadata:
        name: all
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-gpg
        postBuild:
          substitute:
            cluster_env: "local"
            cluster_domain: "acp.local"
            cluster_region: "local"
            cluster_region_domain: "acp.local"
