kind: Service
apiVersion: v1
metadata:
  name: acp-faas-nodejs-proxy
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - name: http
      port: 8080
      protocol: TCP
