apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acp-faas
resources:
  - ../base
  - http-autoscaler-scaleobject-nodejs.yaml
  - http-autoscaler-scaleobject-rego.yaml
  - http-autoscaler-service-nodejs.yaml
  - http-autoscaler-service-rego.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/replicas
replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: HTTPScaledObject
        fieldPaths:
          - spec.hosts.1
          - spec.hosts.2
        options:
          delimiter: "."
          index: 1
