apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - alerts
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - thanos.yaml
  - ssl_exporter.yaml
  - blackbox_exporter.yaml
configMapGenerator:
  - name: grafana-dashboards-acp
    files:
      - dashboards/golang.json
      - dashboards/acp.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: grafana-dashboards-cockroachdb
    files:
      - dashboards/cockroachdb-replicas.json
      - dashboards/cockroachdb-runtime.json
      - dashboards/cockroachdb-sql.json
      - dashboards/cockroachdb-storage.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: grafana-dashboards-timescaledb
    files:
      - dashboards/timescaledb-database.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: grafana-dashboards-kyverno
    files:
      - dashboards/kyverno.json
      - dashboards/kyverno-clusterpolicy-details.json
      - dashboards/kyverno-overview.json
      - dashboards/kyverno-policy-details.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: grafana-dashboards-risk-engine
    files:
      - dashboards/risk-engine.json
      - dashboards/risk-engine-analytics-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: grafana-dashboards-other
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/nginx.json
      - dashboards/request-handling-performance.json
      - dashboards/cert-manager.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml
  - name: ssl-exporter
    files:
      - config.yaml=ssl-exporter-config.yaml
    options:
      disableNameSuffixHash: true
secretGenerator:
  - name: grafana-user
    envs:
      - secret.enc.env
    options:
      disableNameSuffixHash: true
  - name: thanos-objstore
    files:
      - objstore.yml=objstorage.enc.yaml
    options:
      disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
