apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: thanos-objstore
stringData:
  objstore.yml: |-
    type: s3
    config:
      bucket: thanos
      endpoint: minio.minio:9000
      access_key: admin
      secret_key: p@ssw0rd!
      http_config:
        insecure_skip_verify: true
