apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-sql-exporter
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prom-sql-exporter
  template:
    metadata:
      annotations:
        prometheus.io/port: "9237"
        prometheus.io/scrape: "true"
      labels:
        app: prom-sql-exporter
    spec:
      containers:
        - env:
            - name: CONFIG
              value: /config/config.yml
            - name: PGPASSFILE
              value: /pgpass/pgpass
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9237
            initialDelaySeconds: 30
            timeoutSeconds: 10
          name: prom-sql-exporter
          image: ghcr.io/justwatchcom/sql_exporter:v0.5.9@sha256:4afb3069978c74247ac3c19b85efa7d4cd82f78186d25d67d6c4fd3dcb3cdf55
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9237
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9237
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 250m
              memory: 32Mi
            requests:
              cpu: 5m
              memory: 16Mi
          volumeMounts:
            - mountPath: /config
              name: prom-sql-exporter-config
            - mountPath: /pgpass
              name: prom-sql-exporter-pgpass
              readOnly: true
            - mountPath: /tls
              name: prom-sql-exporter-certificate
              readOnly: true
          securityContext:
            runAsUser: 1000
            runAsGroup: 65534
            runAsNonRoot: true
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add: ["NET_BIND_SERVICE"]
      restartPolicy: Always
      volumes:
        - name: prom-sql-exporter-config
          configMap:
            name: prom-sql-exporter-config
        - name: prom-sql-exporter-pgpass
          secret:
            secretName: prom-sql-exporter-pgpass
        - name: prom-sql-exporter-certificate
          readOnly: true
          projected:
            defaultMode: 0600
            sources:
              - secret:
                  name: prom-sql-exporter-certificate
                  items:
                    - key: ca.crt
                      path: ca.crt
                      mode: 0600
                    - key: tls.crt
                      path: tls.crt
                      mode: 0600
                    - key: tls.key
                      path: tls.key
                      mode: 0600
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
kind: Service
apiVersion: v1
metadata:
  name: prom-sql-exporter
spec:
  spec:
  selector:
    app: prom-sql-exporter
  type: ClusterIP
  ports:
    - name: prom-sql-exporter
      port: 9237
      targetPort: 9237
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-sql-exporter-config
data:
  config.yml: |
    ---
    jobs:
    - name: "timescaledb_job"
      interval: '1m'
      connections:
      - 'postgres://postgres:@timescaledb.timescaledb-${cluster_region}.svc.cluster.local:5432/acpdb?sslcert=%2Ftls%2F..data%2Ftls.crt&sslkey=%2Ftls%2F..data%2Ftls.key&sslmode=verify-full&sslrootcert=%2Ftls%2F..data%2Fca.crt'
      queries:
      - name: "timescaledb_agreggation_job_status"
        help: "Timescaledb agreggation job status"
        labels:
          - "hypertable_name"
          - "job_id"
          - "last_run_status"
        values:
          - "count"
        query:  |
                SELECT
                hypertable_name::text,
                  job_id::text,
                CASE
                WHEN last_run_status = 'Success' THEN 1
                ELSE 0
                END AS count
                FROM timescaledb_information.job_stats
                GROUP BY hypertable_name, job_id, last_run_status;
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prom-sql-exporter-certificate
spec:
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  privateKey:
    size: 2048
    algorithm: RSA
  commonName: postgres
  dnsNames:
    - acp
    - root
  secretName: prom-sql-exporter-certificate
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
