apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
spec:
  interval: 6h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: thanos
spec:
  interval: 6h
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
