apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssl-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssl-exporter
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ssl-exporter
subjects:
  - kind: ServiceAccount
    name: ssl-exporter
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: ssl-exporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-exporter
data:
  config.yaml: |
    modules:
      tcp:
        prober: tcp
      kubernetes:
        prober: kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-exporter
  app.kubernetes.io/instance: ssl-exporter
  app.kubernetes.io/name: ssl-exporter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: ssl-exporter
      app.kubernetes.io/name: ssl-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ssl-exporter
        app.kubernetes.io/name: ssl-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9219"
    spec:
      securityContext:
        fsGroup: 100
      containers:
        - name: ssl-exporter
          image: ribbybibby/ssl-exporter:2.4.3@sha256:f6812639a073f8eedc922e0423a57becd6302ccd04a4182108523e4ff83a2bc1
          imagePullPolicy: IfNotPresent
          args:
            - --web.probe-path=/probe
            - --web.listen-address=:9219
            - --config.file=/config/config.yaml
          ports:
            - name: tcp
              containerPort: 9219
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 100
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /
              port: tcp
          readinessProbe:
            httpGet:
              path: /
              port: tcp
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 16Mi
      volumes:
        - name: config
          configMap:
            name: ssl-exporter
      serviceAccountName: ssl-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: ssl-exporter
spec:
  ports:
    - name: ssl-exporter
      protocol: TCP
      port: 9219
      targetPort: 9219
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: ssl-exporter
    app.kubernetes.io/name: ssl-exporter
