apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno
resources:
  - ../base
  - repository.yaml
  - policy-reporter.yaml
  - kyverno-policies.yaml
  - policies/best-practices
  - policies/exceptions
  - policies/other
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta2
      kind: HelmRelease
      name: kyverno
    path: release.yaml
