apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  releaseName: kyverno-policies
  chart:
    spec:
      chart: kyverno-policies
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      version: 3.0.4 # helm:autoupdate:kyverno-policies-prod
  interval: 1m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kyverno/kyverno/blob/main/charts/kyverno-policies/values.yaml
  values:
    podSecurityStandard: restricted
    validationFailureAction: Enforce
