apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
spec:
  releaseName: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
      version: 2.24.2
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml
  values:
    nodeSelector:
      clusterCritical: "true"
    tolerations:
      - key: CriticalAddonsOnly
        value: "true"
        effect: NoSchedule
    monitoring:
      enabled: true
      grafana:
        dashboards:
          enabled: false
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
      limits:
        memory: 512Mi
