apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
spec:
  releaseName: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: kyverno
      version: 2.19.4 # helm:autoupdate:policy-reporter-prod
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml
  values:
    monitoring:
      enabled: true
      grafana:
        dashboard:
          enabled: false
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
      limits:
        memory: 256Mi
