apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timescaledb-${cluster_region}
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - pdb.yaml
  - tls.yaml
  - secret-patroni.yaml
  - configmap-post-init.yaml
