apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: timescaledb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: timescaledb
      app.kubernetes.io/component: timescaledb
