apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: timescaledb
spec:
  releaseName: timescaledb
  chart:
    spec:
      chart: timescaledb-single
      sourceRef:
        kind: HelmRepository
        name: timescaledb
        namespace: timescaledb-${cluster_region}
      version: 0.30.0 # helm:autoupdate:timescaledb-single-prod
  interval: 25m
  timeout: 24m30s
  #  https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values.yaml
  values:
    replicaCount: 3
    readinessProbe:
      initialDelaySeconds: 30
    image:
      repository: timescaledev/timescaledb-ha
      tag: pg14.9-ts2.12.1 # {"$imagepolicy": "timescaledb-us-east-1:timescaledb-image-policy-prod:tag"}
    secrets:
      # https://github.com/timescale/timescaledb-kubernetes/issues/346
      credentialsSecretName: timescaledb-credentials
      certificateSecretName: timescaledb-certificate
      pgbackrestSecretName: timescaledb-pgbackrest
    patroni:
      bootstrap:
        dcs:
          postgresql:
            parameters:
              ssl_ca_file: "/etc/certificate/ca.crt"
      postgresql:
        pg_hba:
          - local     all             postgres                              peer
          - local     all             all                                   md5
          - hostnossl all,replication all                all                reject
          - hostssl   all             all                127.0.0.1/32       md5
          - hostssl   all             all                ::1/128            md5
          - hostssl   replication     standby            all                md5
          - hostssl   all             all                all                cert
    postInit:
      - configMap:
          name: timescale-post-init
    persistentVolumes:
      data:
        size: 2Gi
      wal:
        size: 2Gi
    backup:
      enabled: true
      pgBackRest:
        repo1-path: /
        repo1-type: s3
        repo1-s3-bucket: timescaledb
        repo1-s3-uri-style: path
        repo1-storage-ca-file: /etc/certificate/ca.crt
        repo1-retention-full-type: time
        repo1-retention-full: 30
      jobs:
        - name: full-daily-repo1
          type: full
          schedule: "10 3 * * *"
        - name: incr-hourly-repo1
          type: incr
          schedule: "10 0-2,6-23 * * *"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 2G
    tolerations:
      - key: timescaledb
        value: "true"
        effect: NoSchedule
    nodeSelector:
      timescaledb: "true"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "timescaledb"
                  release: "timescaledb"
                  cluster-name: "timescaledb"
          - weight: 100
            podAffinityTerm:
              topologyKey: "topology.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  app: "timescaledb"
                  release: "timescaledb"
                  cluster-name: "timescaledb"
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              group: "batch"
              kind: CronJob
              name: timescaledb-incr.*repo1
              version: v1
            patch:
              - op: add
                path: /spec/jobTemplate/spec/activeDeadlineSeconds
                value: 600
              - op: add
                path: /spec/jobTemplate/spec/template/spec/tolerations
                value:
                  - key: timescaledb
                    value: "true"
                    effect: NoSchedule
              - op: add
                path: /spec/jobTemplate/spec/template/spec/nodeSelector
                value:
                  timescaledb: "true"
              - op: replace
                path: /spec/jobTemplate/spec/template/spec/containers/0/args/9
                value: '{"type": "incr", "repo": "1"}'
              - op: add
                path: /spec/jobTemplate/spec/template/spec/securityContext
                value:
                  fsGroup: 1000
              - op: add
                path: /spec/jobTemplate/spec/template/spec/containers/0/securityContext
                value:
                  runAsUser: 1000
                  runAsGroup: 1000
                  runAsNonRoot: true
                  allowPrivilegeEscalation: false
                  seccompProfile:
                    type: RuntimeDefault
                  capabilities:
                    drop:
                      - ALL
          - target:
              group: "batch"
              kind: CronJob
              name: timescaledb-full.*repo1
              version: v1
            patch:
              - op: add
                path: /spec/jobTemplate/spec/activeDeadlineSeconds
                value: 600
              - op: add
                path: /spec/jobTemplate/spec/template/spec/tolerations
                value:
                  - key: timescaledb
                    value: "true"
                    effect: NoSchedule
              - op: add
                path: /spec/jobTemplate/spec/template/spec/nodeSelector
                value:
                  timescaledb: "true"
              - op: replace
                path: /spec/jobTemplate/spec/template/spec/containers/0/args/9
                value: '{"type": "full", "repo": "1"}'
              - op: add
                path: /spec/jobTemplate/spec/template/spec/securityContext
                value:
                  fsGroup: 1000
              - op: add
                path: /spec/jobTemplate/spec/template/spec/containers/0/securityContext
                value:
                  runAsUser: 1000
                  runAsGroup: 1000
                  runAsNonRoot: true
                  allowPrivilegeEscalation: false
                  seccompProfile:
                    type: RuntimeDefault
                  capabilities:
                    drop:
                      - ALL
          - target:
              group: "apps"
              kind: StatefulSet
              name: timescaledb
              version: v1
            patch:
              - op: add
                path: /spec/template/spec/containers/1/volumeMounts/-
                value:
                  mountPath: /etc/certificate
                  name: certificate
                  readOnly: true
