# Production Readiness - Use Your Own Secret
apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-credentials
type: Opaque
stringData:
  PATRONI_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:OXiDjExzc2u5,iv:G9PbD2EaWbV7TMaPB3lbT6RW5+MHgZ4TNgvAH4w9mjA=,tag:OZatY0S5r4OCic2P9gR4lA==,type:str]
  PATRONI_REPLICATION_PASSWORD: ENC[AES256_GCM,data:apcYsG6W25Sl,iv:h/fK4cYwxkqJ7epPffzsXxanWaZ2wKKnkVnh31wJETQ=,tag:1q4Y7p/kFnBYed1TDSZR1w==,type:str]
  PATRONI_admin_PASSWORD: ENC[AES256_GCM,data:WFQLvoBdJjRs,iv:DvjJiG8ay2mDzhdoossOKnY7fyNwzsU/XFV3H7Bwh4U=,tag:nhqGliBKteCIFVTpUOxSVQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-10-06T11:28:59Z"
  mac: ENC[AES256_GCM,data:dxulla5j7s/kyIBURMFdyIxw/t5SurvQeftruAL/2xlrMKzx5efByPGq+SddxhEUZg4q9HLY5qZQZAwRakz2ve3Q4S4vYR3Gmyat2tfqxRqB8GL5rXrgGWzRhVjO3lA4/+DA5rfM69S7Ggh0IBMsObRUjBrjFPHL32bW8QoMSpU=,iv:WpEuO6RW2+Oq9WNsiiUm2vozDECD49+yG5N8iPIVFtM=,tag:EBayLrGSE+Py6o2RymTzvQ==,type:str]
  pgp:
    - created_at: "2023-10-06T11:28:59Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA8acJXA92K4RAQwAsuKTIOL1XUd+0hAfM7ihCWfT7jB4+eD1fHREUbCwwpVX
        0P+sA641XUy4lGNDdQMX5vfkLH8q9Z+TuQKKLgtgurIHmSDlAH2Flc234GJlri4s
        ZKqx1s4Tmv+/NdijPANbZZNafezc0Iu4Lw+gUu3RD3JIBqH9bJ2yyX6w1GGyvGXG
        yBpCs0wbh20waBLyCr/9UpWXvbfDvW9V2tUnoz/sxGlyx/ckg74eWq56/4yV/2MS
        cHQVtYiPrKmASoWo+h4GckiZhBTH2rP8DZ/VXc9M46GR+QfgvCbCmh6Kh3nBnZ7L
        JtpTX3+8SLsD7w/tQnDSQBpo0V8X6a6TMupN/VKHxi2JDgNfypTnLPhlW8k98RyO
        zriXbOm1MgsyMw7wLLmbP85r8xJdbl+pFDVcDmcJt0Au48yK3WYR83ar8Nr9iJ53
        dZQKa464n+z3yTVo64Qg2AcvYYN9flWPcKRv4u6qjedqTJSfsUAA1aSvEccZGqT6
        o6LAeDN4kZo6eDyJB71f0l4BFnkztQ1+WrEl5tvqkeLNqZk9aFAiUHVTAsccJgee
        tkf9E4aDzQiyMadtTBwSdywJwk7PsTNdL28uiUsMn1VfLE8n30FHhqv358BiCKSA
        yOdo7E5SrQcoceBLe82+
        =DPcx
        -----END PGP MESSAGE-----
      fp: 379B2FD0571BABB20DDF66F7C88D9F4D45AC1770
  encrypted_regex: ^(data|stringData)$
  version: 3.8.0
