apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: timescaledb
spec:
  values:
    replicaCount: 1
    backup:
      enabled: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              name: timescaledb
              version: v1
            patch: |-
              - op: add
                path: /spec/selector/role
                value: primary
