apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spicedb-operator
resources:
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - deployment.yaml
  - namespace.yaml
  - service_account.yaml
images:
  - name: authzed/spicedb-operator
    newTag: v1.12.0 # {"$imagepolicy": "spicedb-operator:spicedb-operator-image-policy-prod:tag"}
