apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - tls.yaml
secretGenerator:
  - name: apm
    envs:
      - secret.enc.env
generatorOptions:
  disableNameSuffixHash: true
