apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
spec:
  releaseName: opentelemetry-collector
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-collector
      version: 0.116.0
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml
  values:
    mode: "daemonset"
    image:
      repository: otel/opentelemetry-collector-k8s
    command:
      name: otelcol-k8s
    service:
      enabled: true
      internalTrafficPolicy: Cluster
    config:
      extensions:
        file_storage:
          directory: /var/lib/otelcol/data
          compaction:
            directory: /var/lib/otelcol/tmp
            on_rebound: true
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
              tls:
                cert_file: /tls/tls.crt
                key_file: /tls/tls.key
      exporters:
        otlp/elastic-local:
          endpoint: apm.elastic:8200
          tls:
            ca_file: "/tls/ca.crt"
          headers:
            Authorization: "Bearer $${APM_LOCAL_TOKEN}"
          sending_queue:
            storage: file_storage
          retry_on_failure:
            enabled: true
      # https://opentelemetry.io/docs/collector/configuration/#service
      service:
        telemetry:
          logs:
            level: "warn"
          metrics:
            level: "basic"
        extensions: [health_check, file_storage]
        pipelines:
          traces:
            exporters: [debug, otlp/elastic-local]
    extraEnvs:
      - name: APM_LOCAL_TOKEN
        valueFrom:
          secretKeyRef:
            name: apm
            key: apm-server.auth.secret_token
    extraVolumes:
      - name: opentelemetry-tls
        secret:
          secretName: opentelemetry-tls
      - name: data
        hostPath:
          path: /var/lib/otelcol/data
          type: DirectoryOrCreate
      - name: tmp
        hostPath:
          path: /var/lib/otelcol/tmp
          type: DirectoryOrCreate
    extraVolumeMounts:
      - mountPath: /tls
        name: opentelemetry-tls
        readOnly: true
      - name: data
        mountPath: /var/lib/otelcol/data
      - name: tmp
        mountPath: /var/lib/otelcol/tmp
    ports:
      metrics:
        enabled: true
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
        add: ["NET_BIND_SERVICE"]
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 2Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: compute
                  operator: In
                  values:
                    - "true"
            - matchExpressions:
                - key: faas
                  operator: In
                  values:
                    - "true"
            - matchExpressions:
                - key: risk-engine
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: compute
        value: "true"
        effect: NoSchedule
      - key: faas
        value: "true"
        effect: NoSchedule
      - key: risk-engine
        value: "true"
        effect: NoSchedule
    serviceMonitor:
      enabled: true
