apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opentelemetry-cert
spec:
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  privateKey:
    size: 2048
    algorithm: RSA
  dnsNames:
    - localhost
    - opentelemetry-collector
    - opentelemetry-collector.observability
    - opentelemetry-collector.observability.svc.cluster.local
  secretName: opentelemetry-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
