# Most (if not all) fixed in newest version of selenium-hub charts, requires upgrade in order to fix them
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-capabilities-strict-acp-tests-selenium
spec:
  background: true
  exceptions:
    - policyName: disallow-capabilities-strict
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Deployment
            - ReplicaSet
          namespaces:
            - acp-tests-selenium
            - acp-tests-selenium-internal
          names:
            - "selenium-*"
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-privilege-escalation-acp-tests-selenium
spec:
  background: true
  exceptions:
    - policyName: disallow-privilege-escalation
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Deployment
            - ReplicaSet
          namespaces:
            - acp-tests-selenium
            - acp-tests-selenium-internal
          names:
            - "selenium-*"
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: require-run-as-nonroot-acp-tests-selenium
spec:
  background: true
  exceptions:
    - policyName: require-run-as-nonroot
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Deployment
            - ReplicaSet
          namespaces:
            - acp-tests-selenium
            - acp-tests-selenium-internal
          names:
            - "selenium-*"
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: restrict-seccomp-strict-acp-tests-selenium
spec:
  background: true
  exceptions:
    - policyName: restrict-seccomp-strict
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Deployment
            - ReplicaSet
          namespaces:
            - acp-tests-selenium
            - acp-tests-selenium-internal
          names:
            - "selenium-*"
