apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: disallow-capabilities-strict-acp
spec:
  background: true
  exceptions:
    - policyName: disallow-capabilities-strict
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Deployment
            - ReplicaSet
          namespaces:
            - acp
            - acp-internal
          names:
            - "acp-primary-*"
---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: disallow-privilege-escalation-acp
spec:
  background: true
  exceptions:
    - policyName: disallow-privilege-escalation
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Deployment
            - ReplicaSet
          namespaces:
            - acp
            - acp-internal
          names:
            - "acp-primary-*"
