apiVersion: v1
kind: Service
metadata:
  name: fortune-teller-service
spec:
  selector:
    app: fortune-teller-app
  ports:
  - port: 50051
    name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-teller-app
  labels:
    app: fortune-teller-app
  annotations:
    services.k8s.cloudentity.com/spec-url: "https://raw.githubusercontent.com/cloudentity/acp-on-k8s/master/examples/fortune-teller/service.proto"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-teller-app
  template:
    metadata:
      labels:
        app: fortune-teller-app
    spec:
      containers:
      - name: fortune-teller-app
        image: quay.io/kubernetes-ingress-controller/grpc-fortune-teller:0.1
        ports:
        - containerPort: 50051
          name: grpc
