apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cockroachdb-${cluster_region}
resources:
  - ../base
configMapGenerator:
  - name: cockroachdb-provision
    behavior: replace
    files:
      - cockroachdb-provision.sh
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: crdbcluster.yaml
