kind: ServiceAccount
apiVersion: v1
metadata:
  name: cockroachdb-provision
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-provision
spec:
  template:
    spec:
      imagePullSecrets:
        - name: artifactory
      serviceAccountName: cockroachdb-provision
      restartPolicy: Never
      containers:
        - name: cockroachdb-client
          image: cockroachdb/cockroach:v24.2.4
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          args:
            - -c
            - /scripts/cockroachdb-provision.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: client-certs-root
              mountPath: /client-certs-root
      volumes:
        - name: scripts
          configMap:
            name: cockroachdb-provision
            defaultMode: 0755
        - name: client-certs-root
          projected:
            defaultMode: 0400
            sources:
              - secret:
                  name: cockroachdb-client-tls
                  items:
                    - key: ca.crt
                      path: ca.crt
                      mode: 0400
                    - key: tls.crt
                      path: client.root.crt
                      mode: 0400
                    - key: tls.key
                      path: client.root.key
                      mode: 0400
