apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cockroachdb-${cluster_region}
resources:
  - namespace.yaml
  - operator.yaml
  - crdbcluster.yaml
  - tls.yaml
  - job.yaml
images:
  - name: cockroachdb/cockroach
    newTag: v24.2.4
configMapGenerator:
  - name: cockroachdb-provision
    files:
      - cockroachdb-provision.sh
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
