apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acp
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - ../../../secrets/base/registry.yaml
secretGenerator:
  - name: secret
    files:
      - secret.yaml=secret.enc.yaml
  - name: client-secret
    envs:
      - client.enc.env
generatorOptions:
  disableNameSuffixHash: true
