apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acp
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - client.yaml
  - secret.yaml
  - ../../../secrets/base/registry.yaml
