# Production Readiness - Use Your Own Secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret
stringData:
  embedded_idps.yaml: ""
  risk_engine.yaml: ""
  secret.yaml: ENC[AES256_GCM,data:oaFg2g25tDgFiQ7pJywNKawDWnB50Vrv0tRSVJc8WIVJNw/aPApeADzOjUHjRQ8iQ1KUr7Ag31YFOxn/nwBthZVkZdWSfbrXvwCAaLZhD5FALTU0PHcrQmKLEKhBpcENe9vrAVZkxxxJHp8+TJF2dOXo1L9tUZqDO0v2hw7Wo+wAXOD8DuNB7MibHvOawXzVIx8n6ucpH4YTqcmLMXXCaZPqjrT2npSM3dgF/4f/9zP3hjXpRyD1axyk4aE83cMkwXAppaUSp1uSwYkGrL4vYkilhONZCgrOeRQ=,iv:SDLf6Qp3v1yka354bbk9nZAsnDK08xutcNSoBf6FVcQ=,tag:DRCzX5VgekiHWtu4AJ5tXA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-03-27T13:37:24Z"
  mac: ENC[AES256_GCM,data:jHMFd0GNH6u6/LV7wP1HIxLgNNNIop5OB/TOwjS2DiP7gQPdx1XjsWqKeSvJ4KPPDgzTSyGrzuiboYdtfpQooWkAfI2kxnetBDHTvKaUtnaFE2/URuTUx5rEOxnHYSOtfVgXlJ3GLM2afhXoL5luAssxjfw4laxcz87LFY6Ey5s=,iv:H4zmTXJJwlaGWnDCut/GUlN5PBBkKGCzrMS2M1xd8hc=,tag:GizzqJZmNtgF+J906Ad6kQ==,type:str]
  pgp:
    - created_at: "2023-10-06T11:28:59Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA8acJXA92K4RAQv/YGb8mFEosArkb3m0+FGqbrc6UKMFW/QPvJVFppkxPgrT
        n5C3s7OiiLwzrR22bdNTSro6Uaeei9tjKbf5evLqAK+xG0ccEu7oyHi98idxuwiE
        bmpZOnYGTiI9z5/lYr244RGN9ATGRjfGOh5x0kdGaSK3rdCrDh13yZh/A3nUZ3Ht
        fE8f2fEMyXlN7ugG/YjY7OGqscGkLBA831jZxoncyexEmij76UfseaKpAeYpIMCl
        I6+ZdeqJLrdXOr7uAmLl9H/4wftY8TJnCv727pkwCshRG2We9wTIsoBgw6TDy1lS
        F/5CDMD4zwe/kRTjdj5fYdOdIM1OSWeAYUaeoUxbofgC0RZZpmrkmFJBTj1G/aSl
        DSLlmfippOeH8eI00kwsE7rM3EpcHKnEk/C8Dq10k/OwxRZvpR8ip+RU5H2J8wPT
        MsqAqJU8o5GVio+R7OBB42bL0SxJSpB5tSDQgIQSCkZfVGQ8pA+ZYnQTceww15OJ
        oXp+yY8lfrXWVseagamQ0l4BfYCpgCbhbgrj5OHcL0AL2WbDFkqYfA/C6Omsq5eC
        RzonhSrRtg7I7DUR6u5iicUO/2R6hVvJLFH/vbDaUAMZ8Wq9hsmTmQyrveXjz5Q4
        HbAf7SXfpNSNqXBmoilP
        =WO30
        -----END PGP MESSAGE-----
      fp: 379B2FD0571BABB20DDF66F7C88D9F4D45AC1770
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
