apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spicedb
resources:
  - namespace.yaml
  - spicedb.yaml
  - secret.yaml
  - pdb.yaml
  - tls.yaml
images:
  - name: authzed/spicedb
    newTag: v1.39.1@sha256:0a088489f5aa712f00ed7a52580cce026b745eb8158bc0fbd6ddd04b84565923
configurations:
  - kustomizeconfig.yaml
