apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spicedb
resources:
  - namespace.yaml
  - spicedb.yaml
  - secret.yaml
  - pdb.yaml
  - tls.yaml
images:
  - name: authzed/spicedb
    newTag: v1.28.0 # {"$imagepolicy": "spicedb:spicedb-image-policy-prod:tag"}
configurations:
  - kustomizeconfig.yaml
