apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spicedb
resources:
  - namespace.yaml
  - spicedb.yaml
  - secret.yaml
  - pdb.yaml
  - tls.yaml
images:
  - name: authzed/spicedb
    newTag: v1.40.0@sha256:a40bf4b4d2e1dbae936b147789463d0b9e6d44d2b8ebfd6ddbc663963a53919c
configurations:
  - kustomizeconfig.yaml
