apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: spicedb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: spicedb-spicedb
      app.kubernetes.io/name: spicedb
