# Production Readiness - Use Your Own Secret
apiVersion: v1
kind: Secret
metadata:
  name: spicedb-config
stringData:
  datastore_uri: ENC[AES256_GCM,data:zMD6BFZQkf3RTGm+9rXNvR/NkEzeXpJap6rZJ/A2zc06KrLojzcEwyRMFiRWRyrHx4OV1SOg7fYJoICZwKwexGpCbhuT7REvMQBQifbMdBRlaVriT+BTl9QVGF9WPHB7sSfNjE34K6HsSH0TR9ob8IKnQkGrs4v1LOKMwCGfMFSx31iqf0f2TyXFAdbWD9wi5WLw9Gx7rnergGTN4fcelqxDghqi1CjkTLQufrwaYcFfYevshOxwUslhCCAaUn00zY8h/MYspQXkWEPge1uYHEWlzNDJQMN8pBOvSQSX+37ChxKk,iv:89KTPnFRImyT4nZkGJEhiIubBBX2Hk5hrfg2hMohJvk=,tag:kepc57wKcONgqX2UfCl/cw==,type:str]
  preshared_key: ENC[AES256_GCM,data:gDzkBGVlgDnm,iv:Hw0I7EvFwJW52LWadYXDHr733A8H9oLpvIcnwfkGjpk=,tag:KmkTm8538nlAy3EG1qHyFA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-10-06T11:28:59Z"
  mac: ENC[AES256_GCM,data:VLjm17kEfFbCJ3CsGsGNLNhF4uEbXshw9wrXy8a4zBAnhpGNq8tkPwn1S1h+XtI6px1Wq/EDyIbutKB0XVfCpbJtDk7mdjcHzMTkx6+yv3cErHcRwX2EGeJvCIVz8hL93dUZKgjgGKASqXzef7sLwpbOdG7YZo7TyBK1kze+puY=,iv:Rjf6QPoNxQek4edrIa/fODImneW0nGbzlNuG2nB+rjE=,tag:Uj5GD1ZuDC+drHkVD3Ag8w==,type:str]
  pgp:
    - created_at: "2023-10-06T11:28:59Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA8acJXA92K4RAQv9HI1FhzH5QzWLMeushegmt5U14NDJ0fzs/u3QWioe9+1K
        q3Tvft0PAjzviNVLTZS957rLk7tlfJShBw0FfMQx82bOjAI5PRf90Dw08Y6F0HQl
        BcsODV5jkXvV1KER37SV8KSKqSDG/paLKnPzIiKnRuTLq0fanCK/XY7+sOaV2pVp
        bAVefPUnxLxingfk/vsBClZY03Ihja48f6KW4ijanpFLUzK0LjksUAdrmhJZae6T
        JfqO8c/rehJfq0gNLLD2Se96JnYJ22Oryzw5XXlsceV6Jfeab9YL5YWshV35n6qA
        dArCP8fhokEuQMInPYD8Zjnw63gCDsU7idQowgYlkLsZwfqiuRDPY4ZHepoFUWR2
        yK4r68uZ6BcrXMz82zYTQT4fW/VJDt1kIeOq6aZxXkBdvQEy9QPV6s1txjVVxYIA
        1aPR8t7e07/fCkXwDXDEIwUCq+U9vomnb+i+Hm3ekcaHojQn0liBiaiBGr6WJz1S
        cf41tbekqR8JK/qiv+iP0l4BfOwk+76tvQMeiYqo6uysm+5bcauMRDnroFA3aWp1
        irfCG9SuwE2TAfnoELFMeqSaTSx+lZl7Mcz5HW6lzq71L5P7TbMeOKz9PMJnsSn/
        M/Sk2aSCSzWKKq/VpVpH
        =5ehY
        -----END PGP MESSAGE-----
      fp: 379B2FD0571BABB20DDF66F7C88D9F4D45AC1770
  encrypted_regex: ^(data|stringData)$
  version: 3.8.0
