apiVersion: v1
kind: Secret
metadata:
  name: spicedb-config
stringData:
  datastore_uri: postgres://acp@cockroachdb-local-public.cockroachdb-${cluster_region}:26257/${cockroachdb_spicedb}?sslcert=%2Fspicedb-db-tls%2Ftls.crt&sslkey=%2Fspicedb-db-tls%2Ftls.key&sslmode=verify-full&sslrootcert=%2Fspicedb-db-tls%2Fca.crt
