apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: spicedb
spec:
  config:
    image: authzed/spicedb
    replicas: 3
    datastoreEngine: cockroachdb
    tlsSecretName: spicedb-tls
    datastoreTLSSecretName: spicedb-client-tls
    dispatchUpstreamCASecretName: spicedb-tls
    extraPodLabels:
      app.kubernetes.io/name: spicedb
  secretName: spicedb-config
  patches:
    - kind: Deployment
      patch:
        metadata:
          annotations:
            secret.reloader.stakater.com/reload: "spicedb-tls,spicedb-client-tls"
    - kind: Deployment
      patch:
        spec:
          name: spicedb
          template:
            spec:
              containers:
                - name: spicedb-spicedb
                  securityContext:
                    allowPrivilegeEscalation: false
                    seccompProfile:
                      type: RuntimeDefault
                    capabilities:
                      drop:
                        - ALL
                      add: ["NET_BIND_SERVICE"]
              nodeSelector:
                spicedb: "true"
              tolerations:
                - key: "spicedb"
                  value: "true"
                  effect: NoSchedule
              affinity:
                podAntiAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchLabels:
                          app.kubernetes.io/instance: spicedb-spicedb
                          app.kubernetes.io/name: spicedb
                      topologyKey: kubernetes.io/hostname
              topologySpreadConstraints:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/instance: spicedb-spicedb
                      app.kubernetes.io/name: spicedb
                  maxSkew: 1
                  topologyKey: topology.kubernetes.io/zone
                  whenUnsatisfiable: ScheduleAnyway
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault

    - kind: Job
      patch:
        spec:
          name: spicedb-migrate
          template:
            spec:
              containers:
                - name: migrate
                  securityContext:
                    allowPrivilegeEscalation: false
                    seccompProfile:
                      type: RuntimeDefault
                    capabilities:
                      drop:
                        - ALL
                      add: ["NET_BIND_SERVICE"]
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
