apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spicedb-cert
spec:
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  privateKey:
    size: 2048
    algorithm: RSA
  dnsNames:
    - localhost
    - spicedb
    - spicedb.spicedb
    - spicedb.spicedb.svc.cluster.local
  secretName: spicedb-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spicedb-client-cert
spec:
  usages:
    - digital signature
    - key encipherment
    - client auth
  privateKey:
    size: 2048
    algorithm: RSA
  dnsNames:
    - localhost
    - spicedb
    - spicedb.spicedb
    - spicedb.spicedb.svc.cluster.local
  commonName: acp
  secretName: spicedb-client-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
