apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: public-nginx
spec:
  releaseName: public
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.12.1
  interval: 20m
  timeout: 19m30s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml
  values:
    controller:
      image:
        allowPrivilegeEscalation: false
      nodeSelector:
        nginx: "true"
      tolerations:
        - operator: Exists
      service:
        type: NodePort
        loadBalancerSourceRanges: []
        ports:
          http: 8080
          https: 8443
        nodePorts:
          http: 30090
          https: 30443
      config:
        large-client-header-buffers: "4 16k"
        use-forwarded-headers: "true"
        annotations-risk-level: Critical
      allowSnippetAnnotations: true
      admissionWebhooks:
        timeoutSeconds: 20
        createSecretJob:
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
        patchWebhookJob:
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
      extraArgs:
        ingress-class: public-nginx
      electionID: ingress-public-leader
      ingressClassResource:
        name: public-nginx
        enabled: true
        default: false
        controllerValue: "k8s.io/public-nginx"
      updateStrategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      lifecycle:
        preStop:
          exec:
            command:
              - sleep
              - "120"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - ingress-nginx
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - public
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - controller
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: controller
              app.kubernetes.io/instance: public
              app.kubernetes.io/name: ingress-nginx
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
          add: ["NET_BIND_SERVICE"]
      resources:
        # Production Readiness - Adjust Pod Resources
        requests:
          cpu: 10m
          memory: 10Mi
        limits:
          memory: 512Mi
