apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: acp-faas-nodejs-v4
spec:
  releaseName: acp-faas-nodejs-v4
  chart:
    spec:
      chart: ./charts/acp-faas
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m
  timeout: 9m30s
  install:
    remediation:
      retries: 3
  values:
    image:
      name: node-env
      tag: "v4-20231201-110927-d511a9a7" # {"$imagepolicy": "acp-faas:node-env-v4-image-policy-prod:tag"}
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: acp-faas
            app.kubernetes.io/instance: acp-faas-nodejs-v4
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
