apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: acp-faas-rego-v5
spec:
  releaseName: acp-faas-rego-v5
  chart:
    spec:
      chart: ./charts/acp-faas
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m
  timeout: 9m30s
  install:
    remediation:
      retries: 3
  values:
    image:
      name: rego-env
      tag: "5" # {"$imagepolicy": "acp-faas:rego-env-v5-image-policy-prod:tag"}
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: acp-faas
            app.kubernetes.io/instance: acp-faas-rego-v5
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
