apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-local-dns
spec:
  releaseName: node-local-dns
  chart:
    spec:
      chart: node-local-dns
      sourceRef:
        kind: HelmRepository
        name: node-local-dns
      version: 2.1.0
  interval: 1m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/deliveryhero/helm-charts/blob/master/stable/node-local-dns/values.yaml
  values:
    config:
      bindIp: true
    serviceMonitor:
      enabled: true
    securityContext:
      seccompProfile:
        type: RuntimeDefault
