apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  releaseName: cloudnative-pg
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: 0.23.0
  interval: 5m
  timeout: 4m30s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
  values:
    crds:
      create: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 2Gi
