apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: http-add-on
spec:
  releaseName: http-add-on
  chart:
    spec:
      chart: keda-add-ons-http
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: keda
      version: 0.8.0 # helm:autoupdate:keda-add-ons-http-prod
  interval: 1m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kedacore/charts/blob/main/http-add-on/values.yaml
  values:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      operator:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
      kuberbacproxy:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
      scaler:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
      interceptor:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
    podSecurityContext:
      operator:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      scaler:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      interceptor:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    operator:
      nodeSelector:
        system: "true"
      tolerations:
        - key: system
          value: "true"
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - keda-add-ons-http-controller-manager
              topologyKey: "kubernetes.io/hostname"
    scaler:
      nodeSelector:
        system: "true"
      tolerations:
        - key: system
          value: "true"
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - keda-add-ons-http-external-scaler
              topologyKey: "kubernetes.io/hostname"
    interceptor:
      nodeSelector:
        system: "true"
      tolerations:
        - key: system
          value: "true"
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - keda-add-ons-http-interceptor
              topologyKey: "kubernetes.io/hostname"
    crds:
      install: false
