apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: crdbclusters.crdb.cockroachlabs.com
    patch: |-
      - op: replace
        path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/nodes/minimum
        value: 1
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      labelSelector: "app.kubernetes.io/part-of=kyverno"
    patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: all
