apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redisinsight
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - tls.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
