apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redisinsight
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - tls.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: redis/redisinsight
    newTag: "2.66.0@sha256:e3af8fca1272243632adba175af4db0c439618f83649d8a12bbf617d3c9ff284"
