apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: redis-credentials
data:
  redis-password: ENC[AES256_GCM,data:fcL3gpnejWoKPhKB,iv:vgdYHRQ7roJCqUIHKpfSsKrXvSctU9pE6/gTdzRty68=,tag:nSE5a0uaaIoXZX3lK4FAAw==,type:str]
  redis-re-password: ENC[AES256_GCM,data:3XzmKodaDE8bM7AG,iv:LrOQSrF/lrbUI+SKz1tJPdyBfp0ZL4W/4jDHaYlk9OE=,tag:uWIQmGVJMLXHq2UrXHmzEg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-11-22T10:39:10Z"
  mac: ENC[AES256_GCM,data:RmLBeZjAY6QbUUWMCb/JBJ63EaAekCxjpaEI6HX07Z7HP731xHoj/Vdj5VjhOxYphdd7mra/d31CbAFR4D7fF4aDs/Cnc/1bT8mDqGW75jO4PY1Df6LdTKb2VAG6bGrYVJT2YvRbyoL6f4PkDR7O3Yd+fJSLm3uMwqEiu/SgDXc=,iv:+zTe+N21HYEoQkl3E8gVYgS9M3z3zhPf78Js54oVj1M=,tag:yWpqkQuaXPuW/r2Sk33jTw==,type:str]
  pgp:
    - created_at: "2024-03-11T10:40:13Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA8acJXA92K4RAQv/V2vnYil7EQy0HHOIFszxrLcY3+gyZ0hjDDJ0C4apbVF4
        yQgZ6FRYwp8RyvaexejjOkJ8oOrUig7Hr3/exP6ha+0k3FRp+3+cYnKtSz7jja/t
        hvWZmPlhXH8J/ouz0B0haUMdTwvrXtaz1D5oFWmkcARhOLDFvPV1orx6acxq8i8O
        IJ64O6Km626TXhEU8VA+ttc1nqAD1D/oskXGo4LWgmQTDdTClQ+wSRdWwXC7N6VP
        nUbhDNm/qTNU5Gl/bUr6xyDtCIbwJl2yTS6+caQ6TirCacY7GV8BfKCBVisiCHIZ
        FKccCiI3ws86v2nR7/UP6oflQg9N0yer7HJnvaQhir4bEvPeow1IByrtpY0KaDDf
        V+tC18Hw1GU+LcE9t1mmZB8uW1D9aYiL39ff/lBDGXl7eXhdKsFOWwq0vsE6bq2j
        4mc9fwoAKrRYSu5G2kZgy5Qo+LUz3JvDW5Fcz+2L0G00Nc/YdbjtC53uYS7/VPq3
        JbXF5kZ/qVTu32WJ+3NN0l4Bn3L1Pe3VRaMbvJo0FNZ9J6TNpMSrp5q0LH9lnQ2T
        fKTt9KKfLRJHCJTPYIRnNvxGhgw7rKHeyqewgxw/L3EmqwpRCT1g5E3UMNLewAPo
        YlLzvBiJNTWJJtQrjsi5
        =oRNl
        -----END PGP MESSAGE-----
      fp: 379B2FD0571BABB20DDF66F7C88D9F4D45AC1770
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
