apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
spec:
  type: ClusterIP
  ports:
    - port: 5540
      targetPort: 5540
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: redisinsight
    app.kubernetes.io/name: redisinsight
