apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      extraArgs:
        skip-tls-verification: true
