apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  values:
    metrics:
      enabled: true
      image:
        tag: 1.61.0
      serviceMonitor:
        enabled: true
      extraArgs:
        skip-tls-verification: true
