apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      extraArgs:
        is-cluster: true
        skip-tls-verification: true
        exclude-latency-histogram-metrics: true
        check-single-streams: "audit,sa_audit"
        streams-exclude-consumer-metrics: true
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
