apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cockroachdb-add-reloader-annotation
  annotations:
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: StatefulSet,Annotation
    policies.kyverno.io/minversion: 1.4.3
    policies.kyverno.io/description: >-
      Add reloader annotation on statefulset created by cockroach operator.
spec:
  failurePolicy: Fail
  rules:
    - name: add-reloader-annotation
      match:
        any:
          - resources:
              kinds:
                - StatefulSet
              namespaces:
                - cockroachdb-${cluster_region}
              names:
                - "cockroachdb-local"
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              secret.reloader.stakater.com/reload: "cockroachdb-node-tls,cockroachdb-client-tls"
