{
 "title": "ACP",
 "tags": [ "acp" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "environment", "label": "Environment", "query": "preprod,prod" },
   {
    "name": "region",
    "label": "Region",
    "query": "us-east-1,us-west-2,eu-west-1,eu-west-2,ap-southeast-2"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(acp_http_duration_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m]) > 0)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.9, rate(acp_http_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0)"
    }
   ]
  },
  {
   "title": "Status Codes over Time (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(acp_http_duration_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m])) by (status_code) OR on() vector(0)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Codes over Time (10m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(acp_http_duration_seconds_count{region=~\"$region\",env=~\"$environment\",status_code=~\"^5..\"}[10m])) by (pod)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(acp_http_duration_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m]) > 0) by (method, status_code, path) OR on() vector(0)",
       "legendFormat": "{{method}} {{status_code}} {{path}}"
      }
     ]
    },
    {
     "title": "Latency (P90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_http_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0) by (method, status_code, path) OR on() vector(0)",
       "legendFormat": "{{ method }} {{ status_code }} {{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Flows Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "acp_http_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"} OR on() vector(0)",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Latency (P90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_load_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0) by (status) OR on() vector(0)",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hazelcast",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Lag",
     "type": "stat",
     "gridPos": { "h": 2, "w": 7, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_hazelcast_lag_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0)"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 9, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(acp_hazelcast_duration_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m]) > 0)"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_hazelcast_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0)"
      }
     ]
    },
    {
     "title": "Latency (P90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_hazelcast_lag_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0) by (type, name) OR on() vector(0)",
       "legendFormat": "{{ type }} {{ name }}"
      }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(acp_hazelcast_duration_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m])) by (entity, operation) OR on() vector(0)",
       "legendFormat": "{{ operation }} {{ entity }} "
      }
     ]
    },
    {
     "title": "Latency (P90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_hazelcast_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0) by (entity, operation) OR on() vector(0)",
       "legendFormat": "{{ operation }} {{ entity }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Lag",
     "type": "stat",
     "gridPos": { "h": 2, "w": 7, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_redis_lag_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0)"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 9, "x": 7, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(acp_redis_duration_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m]) > 0)"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_redis_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0)"
      }
     ]
    },
    {
     "title": "Latency (P90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_redis_lag_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0) by (type, name) OR on() vector(0)",
       "legendFormat": "{{ type }} {{ name }}"
      }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(acp_redis_duration_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m])) by (entity, operation) OR on() vector(0)",
       "legendFormat": "{{ operation }} {{ entity }} "
      }
     ]
    },
    {
     "title": "Latency (P90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_redis_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0) by (entity, operation) OR on() vector(0)",
       "legendFormat": "{{ operation }} {{ entity }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RPS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(acp_postgres_duration_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m]) > 0)"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_postgres_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0)"
      }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(acp_postgres_duration_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m])) by (operation) OR on() vector(0)",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Latency (P90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_postgres_duration_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0) by (operation) OR on() vector(0)",
       "legendFormat": "{{ operation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(acp_sql_queue_lag_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m]))"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(acp_sql_queue_lag_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m]) > 0)"
      }
     ]
    },
    {
     "title": "Lag",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_sql_queue_lag_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m])) > 0)"
      }
     ]
    },
    {
     "title": "Jobs Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(acp_sql_queue_lag_seconds_count{region=~\"$region\",env=~\"$environment\"}[1m])) by (queue) OR on() vector(0)",
       "legendFormat": "{{ queue }}"
      }
     ]
    },
    {
     "title": "Lag (P90)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.9, rate(acp_sql_queue_lag_seconds_bucket{region=~\"$region\",env=~\"$environment\"}[1m]))) by (queue) OR on() vector(0)",
       "legendFormat": "{{ queue }}"
      }
     ]
    },
    {
     "title": "Jobs Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(acp_sql_queue_count{region=~\"$region\",env=~\"$environment\"}[1m])) by (queue) OR on() vector(0)",
       "legendFormat": "{{ queue }}"
      }
     ]
    },
    {
     "title": "Errors Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(acp_sql_queue_error_count{region=~\"$region\",env=~\"$environment\"}[1m])) by (queue, type) OR on() vector(0)",
       "legendFormat": "{{ queue }} {{ type }}"
      }
     ]
    }
   ]
  }
 ]
}