{
 "title": "CRDB Console: Storage ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"cockroachdb-local\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb-local\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Capacity",
   "type": "graph",
   "description": "Usage of disk space across all nodes\n\n**Capacity**: Maximum store size across all nodes. This value may be explicitly set per node using [--store](https://www.cockroachlabs.com/docs/v21.1/cockroach-start.html#store). If a store size has not been set, this metric displays the actual disk capacity.\n\n**Available**: Free disk space available to CockroachDB data across all nodes.\n\n**Used**: Disk space in use by CockroachDB data across all nodes. This excludes the Cockroach binary, operating system, and other system files.\n\n[How are these metrics calculated?](https://www.cockroachlabs.com/docs/v21.1/ui-storage-dashboard.html#capacity-metrics)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "capacity" }
   ],
   "targets": [
    {
     "expr": "sum(sum(capacity{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Max"
    },
    {
     "expr": " sum(sum(capacity_available{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(sum(capacity{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)) - sum(sum(capacity_available{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Live Bytes",
   "type": "graph",
   "description": "Amount of data that can be read by applications and CockroachDB.\n\n**Live**: Number of logical bytes stored in live [key-value pairs](https://www.cockroachlabs.com/docs/v21.1/architecture/distribution-layer.html#table-data) across all nodes. Live data excludes historical and deleted data.\n\n**System**: Number of physical bytes stored in [system key-value pairs](https://www.cockroachlabs.com/docs/v21.1/architecture/distribution-layer.html#table-data).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "live bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(livebytes{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Live"
    },
    {
     "expr": "sum(sum(sysbytes{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Log Commit Latency: 99th Percentile",
   "type": "graph",
   "description": "The 99th %ile latency for commits to the Raft Log. This measures essentially an fdatasync to the storage engine's write-ahead log.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ns", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(raft_process_logcommit_latency_bucket{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Commit Latency: 50th Percentile",
   "type": "graph",
   "description": "The 50th %ile latency for commits to the Raft Log. This measures essentially an fdatasync to the storage engine's write-ahead log.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ns", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,rate(raft_process_logcommit_latency_bucket{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Command Commit Latency: 99th Percentile ",
   "type": "graph",
   "description": "The 99th %ile latency for commits of Raft commands. This measures applying a batch to the storage engine (including writes to the write-ahead log), but no fsync.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ns", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(raft_process_commandcommit_latency_bucket{job=\"cockroachdb-local\", instance=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Command Commit Latency: 50th percentile ",
   "type": "graph",
   "description": "The 50th %ile latency for commits of Raft commands. This measures applying a batch to the storage engine (including writes to the write-ahead log), but no fsync.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ns", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,rate(raft_process_commandcommit_latency_bucket{job=\"cockroachdb-local\", instance=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Amplification",
   "type": "graph",
   "description": "The average number of real read operations executed per logical read operation.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "factor" }
   ],
   "targets": [
    {
     "expr": "avg(avg(rocksdb_read_amplification{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Read Amplification"
    }
   ]
  },
  {
   "title": "SSTables",
   "type": "graph",
   "description": "The number of SSTables in use.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "sstables" }
   ],
   "targets": [
    {
     "expr": "sum(rocksdb_num_sstables{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "SSTables"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "description": "The number of open file descriptors, compared with the file descriptor limit.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "descriptors" }
   ],
   "targets": [
    {
     "expr": "sum(sum(sys_fd_open{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Open"
    },
    {
     "expr": "sum(sum(sys_fd_softlimit{job=\"cockroachdb-local\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Compactions/Flushes",
   "type": "graph",
   "description": "The number of compactions and memtable flushes per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rocksdb_compactions{job=\"cockroachdb-local\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Compactions"
    },
    {
     "expr": "sum(rate(rocksdb_flushes{job=\"cockroachdb-local\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Flushes"
    }
   ]
  },
  {
   "title": "Time Series Writes",
   "type": "graph",
   "description": "The number of successfully written time series samples, and number of errors attempting to write time series, per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(timeseries_write_samples{job=\"cockroachdb-local\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Samples Written"
    },
    {
     "expr": "sum(rate(timeseries_write_errors{job=\"cockroachdb-local\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Time Series Bytes Written",
   "type": "graph",
   "description": "The number of bytes written by the time series system per second.  \nNote that this does not reflect the rate at which disk space is consumed by time series; the data is highly compressed on disk. This rate is instead intended to indicate the amount of network traffic and disk activity generated by time series writes.\nSee the \"databases\" tab to find the current disk usage for time series data.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(timeseries_write_bytes{job=\"cockroachdb-local\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Bytes Written"
    }
   ]
  }
 ]
}