{
 "title": "Risk Engine - Average LOA",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Tenant",
    "label": "Tenant Name",
    "query": "select Upper(t.name) from tenants as t where t.active = true"
   },
   {
    "name": "Org",
    "label": "Organization Name",
    "query": "select upper(o.tenant_org_id) from organizations  as o \ninner join tenants as t on t.id = o.tenant_id \nwhere o.active = true and \nupper(t.name) In($Tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Successful Auths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM risk_process_unit AS rpu\nINNER JOIN tenants AS t ON t.id = rpu.tenant_id\nINNER JOIN organizations AS o ON o.id = rpu.organization_id\nWHERE \n  Upper(t.name) In($Tenant) AND\n  Upper(o.tenant_org_id) IN($Org) AND\n  rpu.auth_status = 'approved' AND\n  rpu.created_at >= $__timeFrom()\n"
    }
   ]
  },
  {
   "title": "Total Failed Auths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nselect count(*) from risk_process_unit as rpu\n inner join organizations as o on o.id = rpu.organization_id\n inner join tenants as t on t.id = rpu.tenant_id\n where \n Upper(t.name) In($Tenant) AND\n Upper(o.tenant_org_id) IN($Org) AND\n rpu.auth_status !='approved' AND \n rpu.auth_status is not null and\n rpu.created_at >= $__timeFrom()"
    }
   ]
  },
  {
   "title": "Total Missing Auth-Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nselect count(*) from risk_process_unit as rpu\n inner join organizations as o on o.id = rpu.organization_id\n inner join tenants as t on t.id = rpu.tenant_id\n where \n Upper(t.name) In($Tenant) AND\n Upper(o.tenant_org_id) IN($Org) AND\n rpu.auth_status is null and\n rpu.created_at >= $__timeFrom()\n"
    }
   ]
  },
  {
   "title": "Ave LOA",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nselect rpu.tenant_id, ROUND(AVG(rpu.overall_score)::NUMERIC * 100, 2) AS average_score_percentage from risk_process_unit as rpu\n inner join organizations as o on o.id = rpu.organization_id\n inner join tenants as t on t.id = rpu.tenant_id\n where \n Upper(t.name) In($Tenant) AND\n Upper(o.tenant_org_id) IN($Org) AND\n rpu.auth_status is not null and\n rpu.created_at >= $__timeFrom() \n group by rpu.tenant_id"
    }
   ]
  },
  {
   "title": "Geolocation",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select rpu.latitude, rpu.longitude  from risk_process_unit rpu\ninner join organizations as o on o.id = rpu.organization_id\ninner join tenants as t on t.id = rpu.tenant_id\nwhere \nUpper(t.name) In($Tenant) AND\nUpper(o.tenant_org_id) IN($Org) AND\n$__timeFilter(rpu.created_at)\norder by rpu.created_at desc  "
    }
   ]
  },
  {
   "title": "Auth methods",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  Upper(rpu.auth_method),\n  COUNT(*) AS count\nFROM risk_process_unit rpu\ninner join organizations as o on o.id = rpu.organization_id\ninner join tenants as t on t.id = rpu.tenant_id\nwhere \nUpper(t.name) In($Tenant) AND\nUpper(o.tenant_org_id) IN($Org) AND\nrpu.created_at >= $__timeFrom()  and\nrpu.auth_status = 'approved'\nGROUP BY rpu.auth_method\norder by count desc\n\n\n"
    }
   ]
  },
  {
   "title": "Platform",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "select count(*) as c, dd.navigator_platform from dbfp_details as dd\ninner join risk_process_unit as rpu on rpu.dbfp_fingerprint = dd.fingerprint\ninner join organizations as o on o.id = rpu.organization_id\ninner join tenants as t on t.id = rpu.tenant_id\nwhere \nUpper(t.name) In($Tenant) AND\nUpper(o.tenant_org_id) IN($Org) AND\n$__timeFilter(dd.created_at)\ngroup by dd.navigator_platform\norder by c desc \n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "select rpu.created_at AS DATE, t.name, o.tenant_org_id, rpu.event, rpu.overall_score::NUMERIC * 100 as LOA, rpu.auth_status, rpu.auth_method, rpu.dbfp_fingerprint, rpu.ip_address, rpu.city, rpu.state, rpu.country from risk_process_unit rpu\ninner join organizations as o on o.id = rpu.organization_id\ninner join tenants as t on t.id = rpu.tenant_id\nwhere \nUpper(t.name) In($Tenant) AND\nUpper(o.tenant_org_id) IN($Org) AND\nrpu.auth_status is not null and\n$__timeFilter(rpu.updated_at) \norder by rpu.updated_at desc limit 100"
    }
   ]
  }
 ]
}