{
 "title": "Risk Engine",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Risk Engine Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(acp_risk_engine_duration_seconds_count[1m]) > 0) by (method, path, status_code)",
     "legendFormat": "{{method}} {{status_code}} {{path}}"
    }
   ]
  },
  {
   "title": "Risk Engine Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.9, rate(acp_risk_engine_duration_seconds_bucket[1m])) > 0) by (method, status_code, path)",
     "legendFormat": "{{ method }} {{ status_code }} {{path}}"
    }
   ]
  },
  {
   "title": "DBFP Loads Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(acp_dbfp_duration_seconds_count[1m]) > 0) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "DBFP Loading Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.9, rate(acp_dbfp_duration_seconds_bucket[1m])) > 0) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}