apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
      version: 12.8.16 # helm:autoupdate:minio-prod
  interval: 1m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml
  values:
    auth:
      existingSecret: minio-admin
    defaultBuckets: "cockroachdb, timescaledb"
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add: ["NET_BIND_SERVICE"]
    podSecurityContext:
      fsGroup: 1001
      seccompProfile:
        type: RuntimeDefault
    tls:
      enabled: true
      existingSecret: minio-tls
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/service-upstream: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: "ca-issuer"
      ingressClassName: private-nginx
      hostname: "minio.tools.${cluster_region}.${cluster_domain}"
      tls: true
