apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fission
spec:
  releaseName: fission
  chart:
    spec:
      chart: fission-all
      sourceRef:
        kind: HelmRepository
        name: fission-charts
        namespace: fission
      version: "1.19.0"
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
  # https://github.com/fission/fission/blob/master/charts/fission-all/values.yaml
  values:
    debugEnv: true
    routerServiceType: ClusterIP
    createNamespace: false
    defaultNamespace: "acp-faas"
    additionalFissionNamespaces:
      - default
    buildermgr:
      securityContext:
        enabled: true
        seccompProfile:
          type: RuntimeDefault
    executor:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      securityContext:
        enabled: true
        seccompProfile:
          type: RuntimeDefault
    kubewatcher:
      securityContext:
        enabled: true
        seccompProfile:
          type: RuntimeDefault
    fetcher:
      resource:
        mem:
          limits: 32Mi
      securityContext:
        enabled: true
        seccompProfile:
          type: RuntimeDefault
    router:
      resources:
        requests:
          memory: 256Mi
      securityContext:
        enabled: true
        seccompProfile:
          type: RuntimeDefault
    storagesvc:
      securityContext:
        enabled: true
        seccompProfile:
          type: RuntimeDefault
    timer:
      securityContext:
        enabled: true
        seccompProfile:
          type: RuntimeDefault
    webhook:
      securityContext:
        enabled: true
        seccompProfile:
          type: RuntimeDefault
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: buildermgr
            spec:
              template:
                spec:
                  containers:
                    - name: buildermgr
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                          add: ["NET_BIND_SERVICE"]

          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: executor
            spec:
              template:
                spec:
                  containers:
                    - name: executor
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                          add: ["NET_BIND_SERVICE"]
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: kubewatcher
            spec:
              template:
                spec:
                  containers:
                    - name: kubewatcher
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                          add: ["NET_BIND_SERVICE"]
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: mqtrigger-keda
            spec:
              template:
                spec:
                  containers:
                    - name: mqtrigger-keda
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                          add: ["NET_BIND_SERVICE"]
                  securityContext:
                    runAsNonRoot: true
                    runAsUser: 10001
                    runAsGroup: 10001
                    fsGroup: 10001
                    seccompProfile:
                      type: RuntimeDefault
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: router
            spec:
              template:
                spec:
                  containers:
                    - name: router
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                          add: ["NET_BIND_SERVICE"]
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: storagesvc
            spec:
              template:
                spec:
                  containers:
                    - name: storagesvc
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                          add: ["NET_BIND_SERVICE"]
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: timer
            spec:
              template:
                spec:
                  containers:
                    - name: timer
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                          add: ["NET_BIND_SERVICE"]
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: webhook
            spec:
              template:
                spec:
                  containers:
                    - name: webhook
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                            - ALL
                          add: ["NET_BIND_SERVICE"]
