apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: timescaledb
spec:
  values:
    prometheus:
      enabled: true
      image:
        tag: v0.16.0
        pullPolicy: IfNotPresent
    podMonitor:
      enabled: true
    backup:
      resources:
        requests:
          memory: 512Mi
        limits:
          memory: 512Mi
