apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: timescaledb
spec:
  values:
    prometheus:
      enabled: true
    podMonitor:
      enabled: true
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              group: "batch"
              kind: CronJob
              name: timescaledb-incr.*repo1
              version: v1
            patch:
              - op: add
                path: /spec/jobTemplate/spec/activeDeadlineSeconds
                value: 600
              - op: add
                path: /spec/jobTemplate/spec/template/spec/tolerations
                value:
                  - key: timescaledb
                    value: "true"
                    effect: NoSchedule
              - op: add
                path: /spec/jobTemplate/spec/template/spec/nodeSelector
                value:
                  timescaledb: "true"
              - op: replace
                path: /spec/jobTemplate/spec/template/spec/containers/0/args/9
                value: '{"type": "incr", "repo": "1"}'
              - op: add
                path: /spec/jobTemplate/spec/template/spec/securityContext
                value:
                  fsGroup: 1000
              - op: add
                path: /spec/jobTemplate/spec/template/spec/containers/0/securityContext
                value:
                  runAsUser: 1000
                  runAsGroup: 1000
                  runAsNonRoot: true
                  allowPrivilegeEscalation: false
                  seccompProfile:
                    type: RuntimeDefault
                  capabilities:
                    drop:
                      - ALL
          - target:
              group: "batch"
              kind: CronJob
              name: timescaledb-full.*repo1
              version: v1
            patch:
              - op: add
                path: /spec/jobTemplate/spec/activeDeadlineSeconds
                value: 600
              - op: add
                path: /spec/jobTemplate/spec/template/spec/tolerations
                value:
                  - key: timescaledb
                    value: "true"
                    effect: NoSchedule
              - op: add
                path: /spec/jobTemplate/spec/template/spec/nodeSelector
                value:
                  timescaledb: "true"
              - op: replace
                path: /spec/jobTemplate/spec/template/spec/containers/0/args/9
                value: '{"type": "full", "repo": "1"}'
              - op: add
                path: /spec/jobTemplate/spec/template/spec/securityContext
                value:
                  fsGroup: 1000
              - op: add
                path: /spec/jobTemplate/spec/template/spec/containers/0/securityContext
                value:
                  runAsUser: 1000
                  runAsGroup: 1000
                  runAsNonRoot: true
                  allowPrivilegeEscalation: false
                  seccompProfile:
                    type: RuntimeDefault
                  capabilities:
                    drop:
                      - ALL
          - target:
              group: "apps"
              kind: StatefulSet
              name: timescaledb
              version: v1
            patch:
              - op: add
                path: /spec/template/spec/containers/1/volumeMounts/-
                value:
                  mountPath: /etc/certificate
                  name: certificate
                  readOnly: true
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: timescaledb-node-cert
                  secret:
                    secretName: timescaledb-node-cert
                    defaultMode: 416
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  mountPath: /etc/timescaledb-node-cert
                  name: timescaledb-node-cert
                  readOnly: true
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: timescaledb-superuser-cert
                  secret:
                    secretName: timescaledb-superuser-cert
                    defaultMode: 416
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  mountPath: /etc/timescaledb-superuser-cert
                  name: timescaledb-superuser-cert
                  readOnly: true
              - op: add
                path: /spec/template/spec/containers/1/resources
                value:
                  limits:
                    memory: 512Mi
          - target:
              group: "rbac.authorization.k8s.io"
              kind: Role
              name: timescaledb
              version: v1
            patch:
              - op: add
                path: /rules/-
                value:
                  apiGroups:
                    - ""
                  resources:
                    - services
                  verbs:
                    - create
