apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: timescaledb
spec:
  values:
    prometheus:
      enabled: true
      image:
        tag: v0.16.0
    podMonitor:
      enabled: true
    backup:
      resources:
        limits:
          memory: 512Mi
