kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.32.1@sha256:6afef2b7f69d627ea7bf27ee6696b6868d18e03bf98167c420df486da4662db6
    extraPortMappings:
      # private ingress
      ## https
      - containerPort: 30444
        hostPort: 9443
        protocol: TCP
      ## http
      - containerPort: 30091
        hostPort: 9080
        protocol: TCP
      # public ingress
      ## https
      - containerPort: 30443
        hostPort: 8443
        protocol: TCP
      ## http
      - containerPort: 30090
        hostPort: 8080
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "nginx=true,topology.kubernetes.io/zone=local"
  - role: worker
    image: kindest/node:v1.32.1@sha256:6afef2b7f69d627ea7bf27ee6696b6868d18e03bf98167c420df486da4662db6
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "faas=true,redis=true,cockroachdb=true,timescaledb=true,risk-engine=true,spicedb=true,clusterCritical=true,system=true,compute=true,qa=true,elastic=true,topology.kubernetes.io/zone=locala"
  - role: worker
    image: kindest/node:v1.32.1@sha256:6afef2b7f69d627ea7bf27ee6696b6868d18e03bf98167c420df486da4662db6
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "faas=true,redis=true,cockroachdb=true,timescaledb=true,risk-engine=true,spicedb=true,clusterCritical=true,system=true,compute=true,qa=true,elastic=true,topology.kubernetes.io/zone=localb"
  - role: worker
    image: kindest/node:v1.32.1@sha256:6afef2b7f69d627ea7bf27ee6696b6868d18e03bf98167c420df486da4662db6
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "faas=true,redis=true,cockroachdb=true,timescaledb=true,risk-engine=true,spicedb=true,clusterCritical=true,system=true,compute=true,qa=true,elastic=true,topology.kubernetes.io/zone=localc"
