apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - clusterissuer.yaml
secretGenerator:
  - name: ca
    files:
      - tls.crt
      - tls.key
    type: "kubernetes.io/tls"
generatorOptions:
  disableNameSuffixHash: true
