apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../base
  - apps.yaml
  - middleware.yaml
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
    patch: |-
      kind: Kustomization
      metadata:
        name: all
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-gpg
        postBuild:
          substitute:
            cluster_env: "local"
            cluster_domain: "acp.local"
            cluster_region: "local"
            cluster_region_domain: "acp.local"
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: acp
      spec:
        path: ./apps/acp/full
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: crds
      spec:
        path: ./crds/full
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: nginx
      spec:
        path: ./infrastructure/nginx/full
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: cockroachdb
      spec:
        path: ./infrastructure/cockroachdb/full
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: redis
      spec:
        path: ./infrastructure/redis/full
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: timescaledb
      spec:
        path: ./infrastructure/timescaledb/full
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: kyverno
      spec:
        path: ./middleware/kyverno/full
        healthChecks:
          - apiVersion: helm.toolkit.fluxcd.io/v2beta1
            kind: HelmRelease
            name: kyverno
            namespace: kyverno
          - apiVersion: helm.toolkit.fluxcd.io/v2beta1
            kind: HelmRelease
            name: kyverno-policies
            namespace: kyverno
          - apiVersion: helm.toolkit.fluxcd.io/v2beta1
            kind: HelmRelease
            name: policy-reporter
            namespace: kyverno
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: cert-manager
      spec:
        path: ./middleware/cert-manager/full
