apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: private-nginx
spec:
  values:
    controller:
      config:
        log-format-upstream:
          $remote_addr - $remote_user [$time_local] "$host" "$request"
          $status $body_bytes_sent "$http_referer" "$http_user_agent"
          $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] [$upstream_addr]
          [$upstream_response_length] [$upstream_response_time] [$upstream_status] $req_id -
          $http_true_client_ip $http_x_forwarded_for
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          scrapeInterval: ""
