apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: public-nginx
spec:
  values:
    controller:
      config:
        log-format-upstream:
          $remote_addr - $remote_user [$time_local] "$host" "$request"
          $status $body_bytes_sent "$http_referer" "$http_user_agent"
          $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] [$upstream_addr]
          [$upstream_response_length] [$upstream_response_time] [$upstream_status] $req_id $opentelemetry_trace_id
          $http_true_client_ip $http_x_forwarded_for
        enable-opentelemetry: "true"
        opentelemetry-config: "/etc/nginx/opentelemetry.toml"
        opentelemetry-operation-name: "$request_method $uri"
        opentelemetry-trust-incoming-span: "true"
        otlp-collector-host: "opentelemetry-collector.observability"
        otlp-collector-port: "4317"
        otel-max-queuesize: "2048"
        otel-schedule-delay-millis: "5000"
        otel-max-export-batch-size: "512"
        otel-service-name: "public-nginx"
        otel-sampler: "AlwaysOn"
        otel-sampler-ratio: "1.0"
        otel-sampler-parent-based: "false"
        server-snippet: |
          opentelemetry_attribute "ingress.namespace" "$namespace";
          opentelemetry_attribute "ingress.service_name" "$service_name";
          opentelemetry_attribute "ingress.name" "$ingress_name";
          opentelemetry_attribute "ingress.upstream" "$proxy_upstream_name";
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          scrapeInterval: ""
      opentelemetry:
        enabled: true
