apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flagger
spec:
  releaseName: flagger
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flagger
      version: 1.38.0 # helm:autoupdate:flagger-prod
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/fluxcd/flagger/blob/main/charts/flagger/values.yaml
  values:
    selectorLabels: "app.kubernetes.io/name,app.kubernetes.io/instance"
    metricsServer: "http://prometheus-prometheus.monitoring:9090"
    meshProvider: "nginx"
    serviceMonitor:
      enabled: true
    leaderElection:
      enabled: true
      replicaCount: 2
    podDisruptionBudget:
      enabled: true
    nodeSelector:
      system: "true"
    tolerations:
      - key: system
        value: "true"
        effect: NoSchedule
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: flagger
                app.kubernetes.io/name: flagger
            topologyKey: kubernetes.io/hostname
    securityContext:
      enabled: true
      context:
        readOnlyRootFilesystem: true
        runAsUser: 10001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
          add: ["NET_BIND_SERVICE"]
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: flagger
              version: v1
            patch: |-
              - op: add
                path: /spec/template/spec/topologySpreadConstraints
                value:
                  - labelSelector:
                      matchLabels:
                        app.kubernetes.io/instance: flagger
                        app.kubernetes.io/name: flagger
                    maxSkew: 1
                    topologyKey: topology.kubernetes.io/zone
                    whenUnsatisfiable: ScheduleAnyway
