apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-problem-detector
spec:
  releaseName: node-problem-detector
  chart:
    spec:
      chart: node-problem-detector
      sourceRef:
        kind: HelmRepository
        name: node-problem-detector
        namespace: kube-system
      version: 2.3.14 # helm:autoupdate:node-problem-detector-prod
  interval: 1m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/deliveryhero/helm-charts/blob/master/stable/node-problem-detector/values.yaml
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        memory: 64Mi
    securityContext:
      privileged: true
      seccompProfile:
        type: RuntimeDefault
