apiVersion: v1
kind: Namespace
metadata:
  name: acp-system
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: docker.cloudentity.io
metadata:
  name: istio-authorizer
  namespace: acp-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-authorizer
  namespace: acp-system
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: istio-authorizer
subjects:
- kind: ServiceAccount
  name: istio-authorizer
  namespace: acp-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-authorizer-auth-delegator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: istio-authorizer
  namespace: acp-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-authorizer
  namespace: acp-system
rules:
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  verbs:
  - "list"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-authorizer-data
  namespace: acp-system
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDjjCCAnYCCQCkYimCrjt5tDANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMC
    VVMxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdTZWF0dGxlMRQwEgYDVQQKDAtDbG91
    ZGVudGl0eTELMAkGA1UECwwCU0UxEzARBgNVBAMMCmFjcC1zeXN0ZW0xIjAgBgkq
    hkiG9w0BCQEWE2luZm9AYWNwLmFjcC1zeXN0ZW0wHhcNMjExMjEzMDA0MDExWhcN
    MjIxMjEzMDA0MDExWjCBiDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAldBMRAwDgYD
    VQQHDAdTZWF0dGxlMRQwEgYDVQQKDAtDbG91ZGVudGl0eTELMAkGA1UECwwCU0Ux
    EzARBgNVBAMMCmFjcC1zeXN0ZW0xIjAgBgkqhkiG9w0BCQEWE2luZm9AYWNwLmFj
    cC1zeXN0ZW0wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBJdr9bgGx
    fE3nHl/oCYYSMpowkGmbSDUijHNA8p47q+7VgC0AXS5iScySiUptfEn8UdilvhKR
    Fdtfz7epp4zsZSLYQpAafmTrBP4eJLE240dm1k0egp6/cho6S7DdrF8loJoJs+84
    GhDJonX5ktIQAXEOc25CBwukxYUk09x+aiqsFD25Ohxpqc/6Yari3ibfhbZ6aDIR
    EDMze34oM95c86DJGg9nuKfdkC44MbcG0kGByF3+JUwLQ2cWU2+8BHN/mW4VTgRS
    yilX2iXwumvtE00GpMr2xoUsLHC3Vetp7en+3hUE/DulcdTQFyXDqipDZIwSfI+O
    2llr+SlsexzxAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAK3p6DRNsJTZhuA5zBey
    QPKlAtYWGa2Y3JdTNg5qR6tbrATD42A05zFmAqCppSKCcOEdg0SrRONXC709IW36
    dE/W1roNrcdQVV2xXdSFt4+7I5pfjdl3hq0xC67fau8QMfAfxHxZe3BnEQinT+bn
    joYu3RdMigwq/36cuuVIOQsKm1ukYH66+sWCRs48yKc3a0o56uLM783Cn3l2KtdQ
    a1gohl732YrZOA45IPu19EuckfiYSfXF6X5Dc6POYRPF+VJVXF3RaZfOEN6so2WW
    eGimUwKTQVKERIMHGwb/WuGlQ1AZEb2GqoRkdIoVqZgNuk9bouikvU2U9yQOf+si
    mqE=
    -----END CERTIFICATE-----
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-authorizer
  namespace: acp-system
  name: istio-authorizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-authorizer
  template:
    metadata:
      labels:
        app: istio-authorizer
      name: istio-authorizer
    spec:
      serviceAccountName: istio-authorizer
      containers:
        - image: docker.cloudentity.io/istio-authorizer:1.16.1
          imagePullPolicy: IfNotPresent
          name: istio-authorizer
          args:
          - --client-id
          - "$(CLIENT_ID)"
          - --client-secret
          - "$(CLIENT_SECRET)"
          - --issuer-url
          - "$(ISSUER_URL)"
          - --disable-service-discovery
          - "true"
          - -insecure-skip-verify
          - --root-ca
          - /data/ca.pem
          env:
          - name: LOGGING_LEVEL
            value: "DEBUG"
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: istio-authorizer-secrets
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: istio-authorizer-secrets
                key: CLIENT_SECRET
          - name: ISSUER_URL
            valueFrom:
              secretKeyRef:
                name: istio-authorizer-secrets
                key: ISSUER_URL
          volumeMounts:
          - mountPath: /data
            name: data
          ports:
          - containerPort: 9001
          readinessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: data
          configMap:
            name: istio-authorizer-data
---
apiVersion: v1
kind: Service
metadata:
  name: istio-authorizer
  namespace: acp-system
  labels:
    app: istio-authorizer
spec:
  ports:
    - port: 9001
      name: grpc
    - port: 9002
      name: http
  selector:
    app: istio-authorizer
