name: test

on:
  push:
    branches-ignore:
      - "master"
    tags-ignore:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.16.0"
          image: "kindest/node:v1.24.6@sha256:97e8d00bc37a7598a0b32d1fabd155a96355c49fa0d4d4790aab0f161bf31be1"
      - uses: azure/setup-helm@v1
        with:
          version: 3.5.4
        id: install
      - name: Login to docker.cloudentity.io
        run: echo "${{ secrets.DOCKER_PWD }}" | docker login docker.cloudentity.io -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Deploy
        env: # Or as an environment variable
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
        run: make all
      - name: Test
        run: make test-prepare test-web-smoke
      - name: Test-clean
        run: make test-clean
      - name: Debug
        if: failure()
        run: make debug
