name: test

on:
  push:
    branches-ignore:
      - "master"
    tags-ignore:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.10.0"
      - uses: azure/setup-helm@v1
        with:
          version: default
        id: install
      - name: Deploy
        run: make all
